/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-b2-4.openapi.json
// Generated by sdk/protocol/generate_b2_4.py; schema digest: 698bd5780bbc68e4c163115884bb2de8e6cd0940bb2bcc795285ba53dbee0695

import {
  B24Error,
  B24Request,
  B24Response,
  B24Transport,
  fetchB24Transport,
  parseCursor,
  readJson,
  responseHeaders,
  stringifyJson,
} from './b24-transport';

export const B24_PROTOCOL_VERSION = "b2-4.v1" as const;
export const B24_SCHEMA_DIGEST = "698bd5780bbc68e4c163115884bb2de8e6cd0940bb2bcc795285ba53dbee0695" as const;
export const B24_MAX_CURSOR = 9223372036854775807n;

/** All int64 values remain a safe number or a bigint; JSON parsing promotes large tokens. */
export type Int64 = number | bigint;
export type Cursor = Int64;

export interface B24Command {
  action: "graph_create_from_roles" | "team_start_from_roles" | "memory_refresh" | "memory_exclude";
  name?: string | null;
  description?: string | null;
  role_ids?: Array<string>;
  workflow_id?: string | null;
  team_id?: string | null;
  team_version?: number | null;
  workflow_run_id?: string | null;
  workspace_or_target?: string | null;
  member_ids?: Array<string>;
  task?: string | null;
  session_id?: string | null;
  record_id?: string | null;
}

export interface B24Result {
  status?: "completed";
  resource_id: string;
  resource_type: string;
  directory: CollaborationDirectory;
}

export interface Budget {
  max_turns?: number;
  max_consecutive_test_failures?: number;
  timeout_seconds?: number;
  max_output_tokens?: number | null;
  max_cost_usd?: number | null;
  max_tool_calls?: number | null;
}

export interface CollaborationDirectory {
  workflows: Array<WorkflowDefinition>;
  teams: Array<TeamDefinition>;
  roles: Array<CollaborationRole>;
}

export interface CollaborationRole {
  id: string;
  name: string;
  model_profile_id: string;
  model_id: string;
  effort: string;
}

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface ContextInspection {
  session_id: string;
  revisions: Array<InspectedContextRevision>;
}

export type ContextReferenceType = "thread" | "item" | "artifact" | "memory";

export interface ContextSourceRef {
  source_type: ContextSourceType;
  source_id: string;
  cursor?: number | null;
  content_hash: string;
}

export type ContextSourceType = "session" | "agent" | "thread" | "item" | "artifact" | "memory" | "tool_schema" | "compaction";

export type ContextVisibility = "role_private" | "session";

export interface ContextWatermark {
  state: ContextWatermarkState;
  context_window?: number | null;
  reserved_output_tokens?: number | null;
  tool_schema_token_estimate?: number | null;
  safety_margin_tokens?: number | null;
  available_input_tokens?: number | null;
  pre_compaction_token_estimate?: number | null;
  input_token_estimate?: number | null;
  estimation_method?: string | null;
}

export type ContextWatermarkState = "green" | "yellow" | "red" | "emergency" | "unknown";

export interface DatasetOwner {
  kind: "plugin_dataset";
  owner_namespace: string;
  dataset_id: string;
  principal_id: string;
}

export type DeliveryMode = "value" | "reference";

export interface EdgeSpec {
  edge_id: string;
  source_node: string;
  source_port: string;
  target_node: string;
  target_port: string;
  condition?: string | null;
  join_mode?: JoinMode;
  delivery_mode?: DeliveryMode;
  loop_back?: boolean;
}

export type FailurePolicy = "fail_workflow" | "skip" | "manual_reconcile";

export interface GraphLimits {
  max_nodes?: number;
  max_edges?: number;
  max_parallel_nodes?: number;
  max_subagents?: number;
  max_recursion_depth?: number;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export type IdempotencyClass = "pure" | "idempotent" | "non_idempotent";

export interface InspectedContextRevision {
  id?: string;
  cursor?: number | null;
  session_id: string;
  agent_id: string;
  thread_id?: string | null;
  workspace_ref?: string | null;
  request_ordinal: number;
  model_id: string;
  prompt_layout: PromptLayout;
  messages: Array<Message>;
  tools: Array<ToolDefinition>;
  blocks: Array<PromptBlock>;
  reference_bindings?: Array<ReferenceBinding>;
  tool_result_stubs?: Array<ToolResultStub>;
  watermark: ContextWatermark;
  compaction_id?: string | null;
  message_ids?: Array<string>;
  source_item_ids?: Array<string>;
  artifact_refs?: Array<string>;
  memory_refs?: Array<string>;
  compaction_refs?: Array<string>;
  source_snapshots?: Array<ContextSourceRef>;
  token_estimate: number;
  source_cursor_start?: number | null;
  source_cursor_end?: number | null;
  source_cursor_namespace?: "items.sequence" | null;
  created_at?: string;
  memory_inspection?: MemoryInspection | null;
}

export type JoinMode = "all" | "any";

export type JsonValue = unknown;

export interface LoopPolicy {
  max_iterations: number;
  max_wall_seconds: number;
  max_output_tokens: number;
  max_cost_usd: number;
  max_subagents: number;
  max_recursion_depth: number;
  max_no_progress_repeats?: number;
  exit_expression: string;
  on_limit_node_id: string;
  on_manual_reconcile_node_id?: string | null;
}

export interface MemoryConditions {
  commit_ref: string | null;
  tree_digest: string | null;
  file_fingerprints: Record<string, unknown>;
  environment_digest: string | null;
  tool_versions: Record<string, unknown>;
  verified_at: string | null;
  valid_from: string;
  valid_until: string | null;
}

export interface MemoryEnabled {
  state: "enabled";
  binding_id: string;
  binding_epoch: number;
  installation_id: string;
  dataset_id: string;
  config_digest: string;
  package_digest: string;
  certification_id: string;
  index_generation: string;
  global_enabled: true;
}

export interface MemoryInspection {
  pack: MemoryPack;
  entries: Array<MemorySelection>;
  counting_method: string;
  refresh?: "frozen" | "explicit_refresh";
  excluded_record_ids?: Array<string>;
  limitation?: string;
}

export interface MemoryPack {
  manifest_id: string;
  manifest_digest: string;
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  run_id: string;
  agent_instance_id: string;
  binding: MemoryEnabled;
  knowledge_cutoff: string;
  policy_revision: number;
  permission_epoch: number;
  selected: Array<MemoryVersionRef>;
  total_token_budget: number;
  token_count: number;
  selection: "automatic_and_explicit";
}

export interface MemorySelection {
  memory: MemoryVersion;
  reason: "explicit" | "task_relevance" | "resident_preference";
  token_count: number;
}

export interface MemoryVersion {
  ref: MemoryVersionRef;
  owner: DatasetOwner;
  kind: "working" | "episodic" | "project";
  content_type: "fact" | "preference" | "episode" | "procedure";
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  role_ids: Array<string>;
  agent_ids: Array<string>;
  content: string;
  sources: Array<SourceRef>;
  evidence: "user_asserted" | "observed" | "tested" | "inferred" | "legacy_unverified";
  sensitivity: "public" | "internal" | "sensitive";
  retention_policy_id: string;
  conditions: MemoryConditions;
  recorded_at: string;
}

export interface MemoryVersionRef {
  dataset_id: string;
  record_id: string;
  version: number;
  content_digest: string;
}

export interface MergeNodePolicy {
  strategy?: MergeStrategy;
  source_writer_keys: Array<string>;
  require_review?: boolean;
  rollback_on_failure?: boolean;
}

export type MergeStrategy = "three_way" | "cherry_pick" | "apply_patch";

export interface Message {
  role: MessageRole;
  content?: string | null;
  tool_calls?: Array<ToolCall>;
  tool_call_id?: string | null;
  name?: string | null;
}

export type MessageRole = "system" | "user" | "assistant" | "tool";

export type NodeKind = "agent" | "tool" | "script" | "condition" | "fan_out" | "join" | "loop" | "human_input" | "approval" | "wait" | "timer" | "subworkflow" | "artifact" | "merge";

export interface NodeSpec {
  node_id: string;
  node_kind: NodeKind;
  input_ports?: Array<PortSpec>;
  output_ports?: Array<PortSpec>;
  agent_or_action_ref?: string | null;
  model_override?: string | null;
  context_policy?: Record<string, unknown>;
  capability_requirements?: Array<string>;
  retry_policy?: RetryPolicy;
  timeout_policy?: TimeoutPolicy | null;
  budget?: Budget | null;
  idempotency_class?: IdempotencyClass;
  workspace_or_target?: string | null;
  failure_policy?: FailurePolicy;
  writes_workspace?: boolean;
  writer_policy?: WriterNodePolicy | null;
  merge_policy?: MergeNodePolicy | null;
  loop_policy?: LoopPolicy | null;
  subworkflow_id?: string | null;
  subworkflow_version?: number | null;
  metadata?: Record<string, unknown>;
}

export interface PersonalScope {
  kind: "personal";
  principal_id: string;
  opt_in_grant_id: string;
}

export interface PortSpec {
  name: string;
  value_type?: string;
  required?: boolean;
}

export interface PromptBlock {
  id?: string;
  revision_id: string;
  position: number;
  block_type: PromptBlockType;
  content: string;
  content_hash: string;
  source_refs?: Array<ContextSourceRef>;
  stable_until?: string | null;
  visibility?: ContextVisibility;
  token_estimate?: number | null;
  cache_eligible?: boolean;
}

export type PromptBlockType = "role_instructions" | "tool_schema" | "explicit_references" | "compaction" | "conversation";

export interface PromptLayout {
  version?: string;
  block_order?: Array<PromptBlockType>;
}

export interface ProtocolNegotiation {
  protocol_version: "b2-4.v1";
  schema_digest: string;
  min_client_version: "b2-4.v1";
  capabilities: Array<string>;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export interface ReferenceBinding {
  id?: string;
  revision_id: string;
  position: number;
  ref_type: ContextReferenceType;
  user_text?: string | null;
  resolved_target: string;
  source_snapshot_hash: string;
  include_mode: ReferenceIncludeMode;
  max_tokens?: number | null;
  visibility?: ContextVisibility;
  resolved_at?: string;
}

export type ReferenceIncludeMode = "inline" | "metadata";

export interface RetryPolicy {
  max_attempts?: number;
  delay_seconds?: number;
}

export interface RunScope {
  kind: "run";
  project_id: string;
  workspace_id: string;
  run_id: string;
  writer_id: string | null;
}

export interface SessionScope {
  kind: "session";
  project_id: string;
  workspace_id: string;
  session_id: string;
}

export interface SourceRef {
  source_type: "item" | "artifact" | "memory_version" | "mailbox_message" | "workflow_event";
  source_id: string;
  revision: number;
  content_digest: string;
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  permission_epoch: number;
  availability: "available" | "deleted" | "revoked" | "unavailable";
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export interface TeamDefinition {
  team_id?: string;
  version?: number;
  members: Array<TeamMember>;
  default_coordinator: string;
  mailbox_policy?: Record<string, unknown>;
  task_board_policy?: Record<string, unknown>;
  artifact_visibility?: string;
  message_visibility_policy?: string;
  max_active_agents?: number;
  max_spawn_depth?: number;
}

export interface TeamMember {
  member_id: string;
  agent_definition_id: string;
  role: string;
  can_coordinate?: boolean;
}

export interface TimeoutPolicy {
  timeout_seconds?: number;
  on_timeout_node_id?: string | null;
}

export interface ToolCall {
  id: string;
  name: string;
  arguments_json?: string;
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
}

export interface ToolResultStub {
  artifact_id: string;
  tool_call_id: string;
  content_hash: string;
  original_size: number;
  stored_size: number;
  summary: string;
  fetch_capability?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface WorkflowDefinition {
  workflow_id?: string;
  version?: number;
  name: string;
  description?: string;
  input_schema?: Record<string, unknown>;
  output_schema?: Record<string, unknown>;
  nodes: Array<NodeSpec>;
  edges?: Array<EdgeSpec>;
  graph_limits?: GraphLimits;
  default_budget?: Budget;
  default_policy?: Record<string, unknown>;
  required_plugins?: Array<string>;
  required_capabilities?: Array<string>;
  locked_role_versions?: Record<string, unknown>;
  locked_provider_versions?: Record<string, unknown>;
  status?: WorkflowDefinitionStatus;
  created_at?: string;
}

export type WorkflowDefinitionStatus = "draft" | "published" | "deprecated";

export interface WorkspaceScope {
  kind: "workspace";
  project_id: string;
  workspace_id: string;
}

export type WriterIsolationKind = "worktree" | "container";

export interface WriterNodePolicy {
  writer_key: string;
  isolation_kind: WriterIsolationKind;
  isolation_ref: string;
  ownership_paths: Array<string>;
}

type OperationParameter = { name: string; in: string; required: boolean; schema: Record<string, unknown> };
type OperationDefinition = {
  method: string; pathTemplate: string; parameters: readonly OperationParameter[];
  requestBody: Record<string, unknown> | null; mutuallyExclusive: readonly (readonly string[])[];
  responses: Record<string, Record<string, unknown>>;
};

const B24_OPERATIONS: Record<string, OperationDefinition> = {
  "negotiateProtocol": {
    "method": "GET",
    "pathTemplate": "/v1/protocol/b2-4",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProtocolNegotiation"
            }
          }
        }
      }
    }
  },
  "getCollaborationDirectory": {
    "method": "GET",
    "pathTemplate": "/v1/b2-4/collaboration",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CollaborationDirectory"
            }
          }
        }
      }
    }
  },
  "inspectContext": {
    "method": "GET",
    "pathTemplate": "/v1/b2-4/context/{session_id}",
    "parameters": [
      {
        "name": "session_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Session Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ContextInspection"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "execute": {
    "method": "POST",
    "pathTemplate": "/v1/b2-4/commands",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/B24Command"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/B24Result"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  }
} as const;

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface B24RequestOptions { idempotencyKey?: string; }
export interface ExecuteOptions {
  idempotencyKey?: string;
}

export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only a bounded recent window per resource and stream scope. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly order = new Map<string, string[]>();
  private readonly latest = new Map<string, Cursor>();
  private readonly scopeOrder: string[] = [];
  constructor(private readonly maxSeenPerScope = 1024, private readonly maxScopes = 1024) {
    if (!Number.isSafeInteger(maxSeenPerScope) || maxSeenPerScope < 1 || !Number.isSafeInteger(maxScopes) || maxScopes < 1) throw new RangeError('cursor tracker bounds must be positive safe integers');
  }

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const parsed = parseCursor(frame.id);
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = BigInt(parsed).toString();
    const scope = this.seen.get(key) ?? new Set<string>();
    const order = this.order.get(key) ?? [];
    if (!this.seen.has(key)) { this.scopeOrder.push(key); while (this.scopeOrder.length > this.maxScopes) { const evictedKey = this.scopeOrder.shift(); if (evictedKey !== undefined) { this.seen.delete(evictedKey); this.order.delete(evictedKey); this.latest.delete(evictedKey); } } }
    if (scope.has(cursor)) return false;
    scope.add(cursor); order.push(cursor);
    while (order.length > this.maxSeenPerScope) { const evicted = order.shift(); if (evicted !== undefined) scope.delete(evicted); }
    this.seen.set(key, scope); this.order.set(key, order);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(parsed) > BigInt(previous)) this.latest.set(key, parsed);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    if (!scope || !streamKind) throw new TypeError('SSE scope is required');
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends B24Error {
  constructor(message: string) { super('protocol_incompatible', message, false, 'refresh_and_retry'); this.name = 'ProtocolNegotiationError'; }
}

function validateProtocolNegotiation(value: unknown): ProtocolNegotiation {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new ProtocolNegotiationError('protocol response is not an object');
  const metadata = value as Record<string, unknown>;
  const required = ['protocol_version', 'schema_digest', 'min_client_version', 'capabilities'];
  if (required.some(field => !Object.prototype.hasOwnProperty.call(metadata, field))) throw new ProtocolNegotiationError('protocol response is missing required metadata');
  if (metadata.protocol_version !== B24_PROTOCOL_VERSION || metadata.min_client_version !== B24_PROTOCOL_VERSION) throw new ProtocolNegotiationError(`unsupported Core protocol: ${String(metadata.protocol_version)}`);
  if (metadata.schema_digest !== B24_SCHEMA_DIGEST) throw new ProtocolNegotiationError(`Core Schema digest mismatch: expected ${B24_SCHEMA_DIGEST}, got ${String(metadata.schema_digest)}`);
  if (!Array.isArray(metadata.capabilities) || metadata.capabilities.some(item => typeof item !== 'string' || item.length === 0)) throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
  return metadata as unknown as ProtocolNegotiation;
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues === 'function') {
    const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  throw new B24Error('crypto_unavailable', 'Secure idempotency key generation is unavailable', false, 'none');
}

function requireIdempotencyKey(value: string): string {
  if (typeof value !== 'string' || !value) throw new TypeError('idempotencyKey must not be empty');
  return value;
}


function pathPart(value: string, label: string): string {
  if (!value) throw new TypeError(`${label} must not be empty`);
  return encodeURIComponent(value);
}

function validateMutuallyExclusive(request: unknown, groups: readonly (readonly string[])[]): void {
  if (groups.length === 0) return;
  if (typeof request !== 'object' || request === null || Array.isArray(request)) throw new TypeError('request body must be an object');
  const record = request as Record<string, unknown>;
  for (const group of groups) {
    if (!Array.isArray(group) || group.length < 2 || group.some(field => typeof field !== 'string' || field.length === 0)) throw new TypeError('invalid mutually-exclusive schema metadata');
    const provided = group.filter(field => record[field] !== undefined && record[field] !== null);
    if (provided.length !== 1) throw new TypeError(`exactly one of ${group.join(', ')} is required`);
  }
}

export class B24Client {
  readonly protocolVersion = B24_PROTOCOL_VERSION;
  readonly schemaDigest = B24_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: B24Transport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(baseUrl = 'http://127.0.0.1:8000', transport: B24Transport = fetchB24Transport, clientVersion = B24_PROTOCOL_VERSION) {
    this.baseUrl = baseUrl.replace(/\/+$/, ''); this.transport = transport; this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestOperation(B24_OPERATIONS.negotiateProtocol, {}, true);
    const metadata = validateProtocolNegotiation(await readJson<unknown>(response));
    this.negotiated = metadata; return metadata;
  }

  private async requestOperation(operation: OperationDefinition, args: { pathParams?: Record<string, string>; query?: Record<string, string | undefined>; headers?: Record<string, string | undefined>; body?: string; bodyValue?: unknown; }, skipNegotiation = false): Promise<B24Response> {
    validateMutuallyExclusive(args.bodyValue, operation.mutuallyExclusive);
    const path = operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, name: string) => { const value = args.pathParams?.[name]; if (value === undefined) throw new TypeError(`missing path parameter: ${name}`); return value; });
    const headers = Object.fromEntries(Object.entries(args.headers ?? {}).filter((entry): entry is [string, string] => entry[1] !== undefined));
    return this.requestRaw({ method: operation.method, path, query: args.query, headers, body: args.body }, skipNegotiation);
  }

  private async requestRaw(request: Omit<B24Request, 'url'> & { path: string; query?: Record<string, string | undefined>; }, skipNegotiation = false): Promise<B24Response> {
    if (!skipNegotiation) await this.negotiateProtocol();
    const url = new URL(`${this.baseUrl}${request.path}`); for (const [key, value] of Object.entries(request.query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    let response: B24Response;
    try { response = await this.transport({ ...request, url: url.toString(), headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) } }); }
    catch (error: unknown) { if (error instanceof B24Error) throw error; throw new B24Error('transport_unavailable', error instanceof Error ? error.message : 'transport request failed', true, 'retry_later'); }
    const headers = responseHeaders(response.headers); this.responseMetadata = { status: response.status, idempotencyKey: headers['idempotency-key'], idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true' };
    if (response.status < 200 || response.status >= 300) throw await B24Error.fromResponse(response); return response;
  }

  async getCollaborationDirectory(): Promise<CollaborationDirectory> {
    const response = await this.requestOperation(B24_OPERATIONS["getCollaborationDirectory"], { headers: { Accept: "application/json" } });
    return readJson<CollaborationDirectory>(response);
  }

  async inspectContext(sessionId: string): Promise<ContextInspection> {
    const response = await this.requestOperation(B24_OPERATIONS["inspectContext"], { pathParams: { "session_id": pathPart(sessionId, "session_id") }, headers: { Accept: "application/json" } });
    return readJson<ContextInspection>(response);
  }

  async execute(request: B24Command, options: ExecuteOptions = {}): Promise<B24Result> {
    const response = await this.requestOperation(B24_OPERATIONS["execute"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<B24Result>(response);
  }

}

export { B24Error };
