/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-b2-6.openapi.json
// Generated by sdk/protocol/generate_b2_6.py; schema digest: 78e8694bdf3b55ff4c9d710e758a1ce1af51f34e6365ad13117f1375542745db

import {
  B26Error,
  B26Request,
  B26Response,
  B26Transport,
  fetchB26Transport,
  parseCursor,
  readJson,
  responseHeaders,
  stringifyJson,
} from './b26-transport';

export const B26_PROTOCOL_VERSION = "b2-6.v1" as const;
export const B26_SCHEMA_DIGEST = "78e8694bdf3b55ff4c9d710e758a1ce1af51f34e6365ad13117f1375542745db" as const;
export const B26_MAX_CURSOR = 9223372036854775807n;

/** All int64 values remain a safe number or a bigint; JSON parsing promotes large tokens. */
export type Int64 = number | bigint;
export type Cursor = Int64;

export type B26Command = SkillCommand | SharingCommand | RemoteMemoryCommand;

export interface B26Dataset {
  dataset_id: string;
  installation_id: string | null;
  principal_id: string;
  revision: number;
  state: string;
}

export interface B26EncryptedReply {
  command_id: string;
  host_id: string;
  device_id: string;
  remote_session_id: string;
  issued_at: string;
  expires_at: string;
  nonce: string;
  ciphertext: string;
}

export interface B26Event {
  cursor: number;
  project_id: string;
  action: string;
  affected_ids: Array<string>;
  occurred_at: string;
}

export interface B26EventPage {
  events: Array<B26Event>;
  next_cursor?: number | null;
}

export interface B26Result {
  status: string;
  message: string;
  affected_ids?: Array<string>;
  state: B26State;
}

export interface B26State {
  project_id: string;
  skills: SkillState;
  sharing: SharingState;
  remote: RemoteMemoryState;
  datasets?: Array<B26Dataset>;
  unresolved_command_ids?: Array<string>;
}

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface DatasetOwner {
  kind: "plugin_dataset";
  owner_namespace: string;
  dataset_id: string;
  principal_id: string;
}

export interface DatasetTransfer {
  dataset_id: string;
  destination_dataset_id: string;
  expected_revision: number;
  from_namespace: string;
  to_namespace: string;
  destination_installation_id: string;
  authorization_grant_id: string;
  mode: "transfer" | "authorized_copy";
  idempotency_key: string;
}

export interface DatasetTransferState {
  transfer_id?: string;
  project_id: string;
  request: DatasetTransfer;
  source_installation_id?: string | null;
  source_consumer_id?: string | null;
  destination_consumer_id: string;
  state?: "pending" | "validated" | "committed" | "revoked" | "blocked";
  revision?: number;
  evidence_refs?: Array<string>;
  reason?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface EncryptedRemoteCommand {
  command_id?: string;
  idempotency_key: string;
  host_id: string;
  device_id: string;
  remote_session_id: string;
  protocol_version: string;
  issued_at: string;
  expires_at: string;
  nonce: string;
  ciphertext: string;
  signature: string;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface MemoryConditions {
  commit_ref: string | null;
  tree_digest: string | null;
  file_fingerprints: Record<string, unknown>;
  environment_digest: string | null;
  tool_versions: Record<string, unknown>;
  verified_at: string | null;
  valid_from: string;
  valid_until: string | null;
}

export interface MemoryVersion {
  ref: MemoryVersionRef;
  owner: DatasetOwner;
  kind: "working" | "episodic" | "project";
  content_type: "fact" | "preference" | "episode" | "procedure";
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  role_ids: Array<string>;
  agent_ids: Array<string>;
  content: string;
  sources: Array<SourceRef>;
  evidence: "user_asserted" | "observed" | "tested" | "inferred" | "legacy_unverified";
  sensitivity: "public" | "internal" | "sensitive";
  retention_policy_id: string;
  conditions: MemoryConditions;
  recorded_at: string;
}

export interface MemoryVersionRef {
  dataset_id: string;
  record_id: string;
  version: number;
  content_digest: string;
}

export interface PersonalScope {
  kind: "personal";
  principal_id: string;
  opt_in_grant_id: string;
}

export interface ProjectWorktreeRegistration {
  registration_id?: string;
  project_id: string;
  workspace_id: string;
  worktree_id: string;
  workspace_ref: string;
  branch_ref: string;
  commit_ref?: string | null;
  tree_digest?: string | null;
  principal_id: string;
  association_revision?: number;
  permission_epoch?: number;
  state?: "active" | "revoked";
  revoked_at?: string | null;
  revoke_reason?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface ProtocolNegotiation {
  protocol_version: "b2-6.v1";
  schema_digest: string;
  min_client_version: "b2-6.v1";
  capabilities: Array<string>;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export interface RemoteMemoryCandidate {
  record_id?: string | null;
  content: string;
  content_type?: "fact" | "preference" | "episode" | "procedure";
  source_refs?: Array<SourceRef>;
  reason: string;
  expected_head_revision?: number | null;
}

export interface RemoteMemoryCommand {
  action: "remote_pack_create" | "remote_pack_revoke" | "remote_upload_review";
  project_id: string;
  target_id: string;
  purpose?: string;
  ttl_seconds?: number;
  query?: string | null;
  record_ids?: Array<string>;
  limit?: number;
  max_tokens?: number;
  max_bytes?: number;
  package_id?: string | null;
  package_digest?: string | null;
  upload?: RemoteMemoryUpload | null;
  session_id?: string | null;
  agent_instance_id?: string | null;
  idempotency_key?: string | null;
}

export interface RemoteMemoryPack {
  package_id?: string;
  package_digest?: string;
  project_id: string;
  dataset_id: string;
  target_id: string;
  purpose: string;
  issued_at: string;
  expires_at: string;
  binding_epoch: number;
  permission_epoch: number;
  revocation_epoch: number;
  entries?: Array<RemoteMemoryPackEntry>;
  token_count: number;
  byte_count: number;
  max_tokens: number;
  max_bytes: number;
  status?: "active" | "revoked" | "expired";
}

export interface RemoteMemoryPackEntry {
  ref: MemoryVersionRef;
  content: string;
  content_type: "fact" | "preference" | "episode" | "procedure";
  sensitivity: "public" | "internal";
  source_refs?: Array<SourceRef>;
}

export interface RemoteMemoryPackSummary {
  package_id: string;
  package_digest: string;
  project_id: string;
  dataset_id: string;
  target_id: string;
  purpose: string;
  issued_at: string;
  expires_at: string;
  status: "active" | "revoked" | "expired";
  entry_count: number;
}

export interface RemoteMemoryRecord {
  ref: MemoryVersionRef;
  content: string;
  content_type: "fact" | "preference" | "episode" | "procedure";
  sensitivity: "public" | "internal";
  source_refs?: Array<SourceRef>;
  head_revision: number;
  currently_usable?: boolean;
}

export interface RemoteMemoryState {
  action: "state" | "remote_pack_create" | "remote_pack_revoke" | "remote_upload_review";
  project_id: string;
  dataset_id?: string | null;
  status: "ready" | "completed" | "pending_review" | "rejected" | "revoked" | "expired" | "outcome_unknown";
  message: string;
  records?: Array<RemoteMemoryRecord>;
  packs?: Array<RemoteMemoryPackSummary>;
  pack?: RemoteMemoryPack | null;
  upload_id?: string | null;
  affected_ids?: Array<string>;
  result_ref?: string | null;
  permission_epoch?: number | null;
  binding_epoch?: number | null;
  expires_at?: string | null;
}

export interface RemoteMemoryUpload {
  upload_id?: string;
  package_id: string;
  package_digest: string;
  project_id: string;
  dataset_id: string;
  target_id: string;
  purpose: string;
  candidates?: Array<RemoteMemoryCandidate>;
  source_refs?: Array<SourceRef>;
  source_digest?: string | null;
  submitted_at?: string;
}

export interface RunScope {
  kind: "run";
  project_id: string;
  workspace_id: string;
  run_id: string;
  writer_id: string | null;
}

export interface SessionScope {
  kind: "session";
  project_id: string;
  workspace_id: string;
  session_id: string;
}

export interface SharingCommand {
  action: "worktree_register" | "worktree_revoke" | "grant_create" | "grant_revoke" | "dataset_transfer_begin" | "dataset_transfer_validate" | "dataset_transfer_commit" | "dataset_transfer_revoke" | "consumer_attach" | "consumer_revoke" | "personal_preference_create" | "writer_memory_bind" | "writer_memory_propose" | "writer_memory_verify" | "writer_memory_promote" | "writer_memory_revoke";
  project_id: string;
  expected_revision?: number | null;
  reason?: string | null;
  registration?: ProjectWorktreeRegistration | null;
  workspace_id?: string | null;
  workspace_path?: string | null;
  registration_id?: string | null;
  grant?: SharingGrant | null;
  grant_id?: string | null;
  transfer?: DatasetTransfer | null;
  transfer_id?: string | null;
  evidence_id?: string | null;
  memory_ref?: MemoryVersionRef | null;
  content?: string | null;
  source_refs?: Array<SourceRef>;
  content_type?: "fact" | "preference" | "episode" | "procedure" | null;
  record_id?: string | null;
  sensitivity?: "public" | "internal" | "sensitive" | null;
  worktree_id?: string | null;
  writer_workspace_id?: string | null;
  graph_run_id?: string | null;
  run_id?: string | null;
  branch_ref?: string | null;
  merge_run_id?: string | null;
  verification_artifact_refs?: Array<string>;
  dataset_id?: string | null;
  installation_id?: string | null;
  consumer_id?: string | null;
  consumer_grant_id?: string | null;
  consumer_purpose?: "primary_engine" | "shared_read" | "export" | "migration" | null;
}

export interface SharingConsumer {
  consumer_id?: string;
  project_id: string;
  dataset_id: string;
  installation_id: string;
  grant_id: string;
  purpose: "primary_engine" | "shared_read" | "export" | "migration";
  state?: "active" | "revoked" | "transferred";
  revision?: number;
  revoked_at?: string | null;
  reason?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface SharingGrant {
  grant_id?: string;
  project_id: string;
  source_dataset_id: string;
  source_scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  target_scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  subject_id: string;
  grantor_id: string;
  purpose: "recall" | "source_read" | "publish" | "share" | "transfer" | "delete";
  memory_refs: Array<MemoryVersionRef>;
  policy_revision?: number;
  permission_epoch?: number;
  expires_at: string;
  revision?: number;
  state?: "active" | "revoked" | "expired";
  revoked_at?: string | null;
  revoke_reason?: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface SharingState {
  contract_version?: "operant-b2-6-sharing.v1";
  project_id: string;
  projection_revision?: number;
  worktrees?: Array<ProjectWorktreeRegistration>;
  grants?: Array<SharingGrant>;
  consumers?: Array<SharingConsumer>;
  transfers?: Array<DatasetTransferState>;
  writer_evidence?: Array<WriterMemoryEvidence>;
  writer_candidates?: Array<WriterMemoryCandidate>;
  personal_preferences?: Array<MemoryVersion>;
}

export interface SkillArtifact {
  artifact_id: string;
  media_type?: string;
  content_hash: string;
  size_bytes: number;
  manifest_hash: string;
  resources: Array<SkillResourceHash>;
}

export interface SkillCommand {
  action: "procedure_propose" | "skill_draft" | "skill_validate" | "skill_publish" | "skill_disable" | "skill_rollback";
  project_id: string;
  skill_id?: string | null;
  record_id?: string | null;
  procedure_ref?: MemoryVersionRef | null;
  content?: string | null;
  sources?: Array<SourceRef>;
  name?: string | null;
  description?: string | null;
  skill_version?: number | null;
  rollback_to_version?: number | null;
  expected_head_revision?: number | null;
  permission_epoch?: number | null;
  reason?: string | null;
}

export interface SkillHead {
  skill_id: string;
  head_revision: number;
  published_version?: number | null;
  state: "draft" | "published" | "disabled" | "revoked" | "blocked";
  permission_epoch: number;
  updated_at: string;
}

export interface SkillResourceHash {
  relative_path: string;
  kind: "manifest" | "script" | "reference";
  size_bytes: number;
  sha256: string;
}

export interface SkillState {
  schema_version?: "operant-b2-6-skills.v1";
  project_id: string;
  skills?: Array<SkillView>;
  cursor?: string;
}

export interface SkillValidation {
  validation_id: string;
  skill_id: string;
  skill_version: number;
  status: "pending" | "passed" | "failed" | "blocked";
  validator_version: string;
  artifact_hash: string;
  source_digest: string;
  issues: Array<SkillValidationIssue>;
  checked_at: string;
}

export interface SkillValidationIssue {
  code: string;
  message: string;
}

export interface SkillVersion {
  skill_id: string;
  version: number;
  name: string;
  description: string;
  procedure_ref: MemoryVersionRef;
  source_refs: Array<SourceRef>;
  source_digest: string;
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  role_ids: Array<string>;
  agent_ids: Array<string>;
  sensitivity: "public" | "internal" | "sensitive";
  artifact: SkillArtifact;
  trust_status: "untrusted_draft" | "validated" | "core_published" | "revoked";
  created_at: string;
}

export interface SkillView {
  skill_id: string;
  version: SkillVersion;
  head: SkillHead;
  validation?: SkillValidation | null;
  trust_status?: "untrusted_draft" | "validated" | "core_published" | "revoked";
  dependency_state?: "active" | "blocked" | "revoked";
  rollback_versions?: Array<number>;
}

export interface SourceRef {
  source_type: "item" | "artifact" | "memory_version" | "mailbox_message" | "workflow_event";
  source_id: string;
  revision: number;
  content_digest: string;
  scope: WorkspaceScope | SessionScope | RunScope | PersonalScope;
  permission_epoch: number;
  availability: "available" | "deleted" | "revoked" | "unavailable";
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface WorkspaceScope {
  kind: "workspace";
  project_id: string;
  workspace_id: string;
}

export interface WriterMemoryCandidate {
  evidence_id: string;
  memory: MemoryVersion;
  project_id: string;
  workspace_id: string;
  worktree_id: string;
  writer_workspace_id: string;
  graph_run_id: string;
  run_id: string;
  branch_ref: string;
  state: "candidate" | "eligible" | "published" | "blocked" | "revoked";
  revision?: number;
}

export interface WriterMemoryEvidence {
  evidence_id?: string;
  memory_ref: MemoryVersionRef;
  candidate_head_revision?: number;
  project_id: string;
  workspace_id: string;
  worktree_id: string;
  writer_workspace_id: string;
  graph_run_id: string;
  run_id: string;
  branch_ref: string;
  base_revision: string;
  base_tree_digest?: string | null;
  merge_run_id?: string | null;
  target_isolation_ref?: string | null;
  target_commit_ref?: string | null;
  target_tree_digest?: string | null;
  verification_artifact_refs?: Array<string>;
  verification_digest?: string | null;
  verification_status?: "pending" | "passed" | "failed" | "unknown";
  state?: "candidate" | "eligible" | "published" | "blocked" | "revoked";
  published_memory_ref?: MemoryVersionRef | null;
  permission_epoch?: number;
  revision?: number;
  reason?: string | null;
  created_at?: string;
  updated_at?: string;
}

type OperationParameter = { name: string; in: string; required: boolean; schema: Record<string, unknown> };
type OperationDefinition = {
  method: string; pathTemplate: string; parameters: readonly OperationParameter[];
  requestBody: Record<string, unknown> | null; mutuallyExclusive: readonly (readonly string[])[];
  responses: Record<string, Record<string, unknown>>;
};

const B26_OPERATIONS: Record<string, OperationDefinition> = {
  "negotiateProtocol": {
    "method": "GET",
    "pathTemplate": "/v1/protocol/b2-6",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProtocolNegotiation"
            }
          }
        }
      }
    }
  },
  "getExperience": {
    "method": "GET",
    "pathTemplate": "/v1/b2-6/projects/{project_id}/experience",
    "parameters": [
      {
        "name": "project_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Project Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/B26State"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getEvents": {
    "method": "GET",
    "pathTemplate": "/v1/b2-6/projects/{project_id}/events",
    "parameters": [
      {
        "name": "project_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Project Id"
        }
      },
      {
        "name": "after_cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 9007199254740991,
          "minimum": 0,
          "default": 0,
          "title": "After Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "minimum": 1,
          "default": 100,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/B26EventPage"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "execute": {
    "method": "POST",
    "pathTemplate": "/v1/b2-6/commands",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/B26Command"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/B26Result"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "queryRemote": {
    "method": "POST",
    "pathTemplate": "/v1/b2-6/remote-query",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/EncryptedRemoteCommand"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/B26EncryptedReply"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  }
} as const;

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface B26RequestOptions { idempotencyKey?: string; }
export interface GetEventsOptions {
  afterCursor?: number;
  limit?: number;
}

export interface ExecuteOptions {
  idempotencyKey?: string;
}

export interface QueryRemoteOptions {
  idempotencyKey?: string;
}

export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only a bounded recent window per resource and stream scope. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly order = new Map<string, string[]>();
  private readonly latest = new Map<string, Cursor>();
  private readonly scopeOrder: string[] = [];
  constructor(private readonly maxSeenPerScope = 1024, private readonly maxScopes = 1024) {
    if (!Number.isSafeInteger(maxSeenPerScope) || maxSeenPerScope < 1 || !Number.isSafeInteger(maxScopes) || maxScopes < 1) throw new RangeError('cursor tracker bounds must be positive safe integers');
  }

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const parsed = parseCursor(frame.id);
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = BigInt(parsed).toString();
    const scope = this.seen.get(key) ?? new Set<string>();
    const order = this.order.get(key) ?? [];
    if (!this.seen.has(key)) { this.scopeOrder.push(key); while (this.scopeOrder.length > this.maxScopes) { const evictedKey = this.scopeOrder.shift(); if (evictedKey !== undefined) { this.seen.delete(evictedKey); this.order.delete(evictedKey); this.latest.delete(evictedKey); } } }
    if (scope.has(cursor)) return false;
    scope.add(cursor); order.push(cursor);
    while (order.length > this.maxSeenPerScope) { const evicted = order.shift(); if (evicted !== undefined) scope.delete(evicted); }
    this.seen.set(key, scope); this.order.set(key, order);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(parsed) > BigInt(previous)) this.latest.set(key, parsed);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    if (!scope || !streamKind) throw new TypeError('SSE scope is required');
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends B26Error {
  constructor(message: string) { super('protocol_incompatible', message, false, 'refresh_and_retry'); this.name = 'ProtocolNegotiationError'; }
}

function validateProtocolNegotiation(value: unknown): ProtocolNegotiation {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new ProtocolNegotiationError('protocol response is not an object');
  const metadata = value as Record<string, unknown>;
  const required = ['protocol_version', 'schema_digest', 'min_client_version', 'capabilities'];
  if (required.some(field => !Object.prototype.hasOwnProperty.call(metadata, field))) throw new ProtocolNegotiationError('protocol response is missing required metadata');
  if (metadata.protocol_version !== B26_PROTOCOL_VERSION || metadata.min_client_version !== B26_PROTOCOL_VERSION) throw new ProtocolNegotiationError(`unsupported Core protocol: ${String(metadata.protocol_version)}`);
  if (metadata.schema_digest !== B26_SCHEMA_DIGEST) throw new ProtocolNegotiationError(`Core Schema digest mismatch: expected ${B26_SCHEMA_DIGEST}, got ${String(metadata.schema_digest)}`);
  if (!Array.isArray(metadata.capabilities) || metadata.capabilities.some(item => typeof item !== 'string' || item.length === 0)) throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
  return metadata as unknown as ProtocolNegotiation;
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues === 'function') {
    const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  throw new B26Error('crypto_unavailable', 'Secure idempotency key generation is unavailable', false, 'none');
}

function requireIdempotencyKey(value: string): string {
  if (typeof value !== 'string' || !value) throw new TypeError('idempotencyKey must not be empty');
  return value;
}


function pathPart(value: string, label: string): string {
  if (!value) throw new TypeError(`${label} must not be empty`);
  return encodeURIComponent(value);
}

function validateMutuallyExclusive(request: unknown, groups: readonly (readonly string[])[]): void {
  if (groups.length === 0) return;
  if (typeof request !== 'object' || request === null || Array.isArray(request)) throw new TypeError('request body must be an object');
  const record = request as Record<string, unknown>;
  for (const group of groups) {
    if (!Array.isArray(group) || group.length < 2 || group.some(field => typeof field !== 'string' || field.length === 0)) throw new TypeError('invalid mutually-exclusive schema metadata');
    const provided = group.filter(field => record[field] !== undefined && record[field] !== null);
    if (provided.length !== 1) throw new TypeError(`exactly one of ${group.join(', ')} is required`);
  }
}

export class B26Client {
  readonly protocolVersion = B26_PROTOCOL_VERSION;
  readonly schemaDigest = B26_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: B26Transport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(baseUrl = 'http://127.0.0.1:8000', transport: B26Transport = fetchB26Transport, clientVersion = B26_PROTOCOL_VERSION) {
    this.baseUrl = baseUrl.replace(/\/+$/, ''); this.transport = transport; this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestOperation(B26_OPERATIONS.negotiateProtocol, {}, true);
    const metadata = validateProtocolNegotiation(await readJson<unknown>(response));
    this.negotiated = metadata; return metadata;
  }

  private async requestOperation(operation: OperationDefinition, args: { pathParams?: Record<string, string>; query?: Record<string, string | undefined>; headers?: Record<string, string | undefined>; body?: string; bodyValue?: unknown; }, skipNegotiation = false): Promise<B26Response> {
    validateMutuallyExclusive(args.bodyValue, operation.mutuallyExclusive);
    const path = operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, name: string) => { const value = args.pathParams?.[name]; if (value === undefined) throw new TypeError(`missing path parameter: ${name}`); return value; });
    const headers = Object.fromEntries(Object.entries(args.headers ?? {}).filter((entry): entry is [string, string] => entry[1] !== undefined));
    return this.requestRaw({ method: operation.method, path, query: args.query, headers, body: args.body }, skipNegotiation);
  }

  private async requestRaw(request: Omit<B26Request, 'url'> & { path: string; query?: Record<string, string | undefined>; }, skipNegotiation = false): Promise<B26Response> {
    if (!skipNegotiation) await this.negotiateProtocol();
    const url = new URL(`${this.baseUrl}${request.path}`); for (const [key, value] of Object.entries(request.query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    let response: B26Response;
    try { response = await this.transport({ ...request, url: url.toString(), headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) } }); }
    catch (error: unknown) { if (error instanceof B26Error) throw error; throw new B26Error('transport_unavailable', error instanceof Error ? error.message : 'transport request failed', true, 'retry_later'); }
    const headers = responseHeaders(response.headers); this.responseMetadata = { status: response.status, idempotencyKey: headers['idempotency-key'], idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true' };
    if (response.status < 200 || response.status >= 300) throw await B26Error.fromResponse(response); return response;
  }

  async getExperience(projectId: string): Promise<B26State> {
    const response = await this.requestOperation(B26_OPERATIONS["getExperience"], { pathParams: { "project_id": pathPart(projectId, "project_id") }, headers: { Accept: "application/json" } });
    return readJson<B26State>(response);
  }

  async getEvents(projectId: string, options: GetEventsOptions = {}): Promise<B26EventPage> {
    const response = await this.requestOperation(B26_OPERATIONS["getEvents"], { pathParams: { "project_id": pathPart(projectId, "project_id") }, query: { "after_cursor": options.afterCursor === undefined ? undefined : String(options.afterCursor), "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<B26EventPage>(response);
  }

  async execute(request: B26Command, options: ExecuteOptions = {}): Promise<B26Result> {
    const response = await this.requestOperation(B26_OPERATIONS["execute"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<B26Result>(response);
  }

  async queryRemote(request: EncryptedRemoteCommand, options: QueryRemoteOptions = {}): Promise<B26EncryptedReply> {
    const response = await this.requestOperation(B26_OPERATIONS["queryRemote"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<B26EncryptedReply>(response);
  }

}

export { B26Error };
