/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-caller-pairing.openapi.json
// Generated by sdk/protocol/generate_caller_pairing.py; schema digest: 0e29335a885862bb0d1f696389cd598b787c577f2f6fbe4b8eeae71cbf06a800

import {
  CallerPairingError,
  CallerPairingRequest,
  CallerPairingResponse,
  CallerPairingTransport,
  fetchCallerPairingTransport,
  parseCursor,
  readJson,
  responseHeaders,
  stringifyJson,
} from './caller-pairing-transport';

export const CALLER_PAIRING_PROTOCOL_VERSION = "caller-pairing.v1" as const;
export const CALLER_PAIRING_SCHEMA_DIGEST = "0e29335a885862bb0d1f696389cd598b787c577f2f6fbe4b8eeae71cbf06a800" as const;
export const CALLER_PAIRING_MAX_CURSOR = 9223372036854775807n;

/** All int64 values remain a safe number or a bigint; JSON parsing promotes large tokens. */
export type Int64 = number | bigint;
export type Cursor = Int64;

export interface CallerChallengeInput {
  ttl_seconds?: number;
}

export interface CallerCommand {
  protocol_version?: "caller-pairing.v1";
  core_epoch_id: string;
  device_id: string;
  request_id: string;
  operation: "list" | "add" | "remove" | "readback" | "continue";
  issued_at: number;
  expires_at: number;
  nonce: string;
  ciphertext: string;
  signature: string;
}

export interface CallerDeviceList {
  items: Array<CallerDeviceView>;
}

export interface CallerDeviceView {
  device_id: string;
  display_name: string;
  signing_key_fingerprint: string;
  core_epoch_id: string;
  scope?: "skill_source.manage";
  expires_at: number;
  state: "active" | "expired" | "revoked" | "needs_pairing";
}

export interface CallerEncryptedReply {
  protocol_version?: "caller-pairing.v1";
  core_epoch_id: string;
  device_id: string;
  request_id: string;
  operation: "pair" | "list" | "add" | "remove" | "readback" | "continue";
  request_hash: string;
  issued_at: number;
  expires_at: number;
  nonce: string;
  ciphertext: string;
  signature: string;
}

export interface CallerPairRequest {
  protocol_version?: "caller-pairing.v1";
  pair_request_id: string;
  ticket_id: string;
  core_epoch_id: string;
  device_id: string;
  device_signing_public_key: string;
  device_exchange_public_key: string;
  scope?: "skill_source.manage";
  issued_at: number;
  expires_at: number;
  nonce: string;
  ciphertext: string;
  signature: string;
}

export interface CallerPairingTicket {
  protocol_version?: "caller-pairing.v1";
  ticket_id: string;
  core_epoch_id: string;
  base_url: string;
  core_exchange_public_key: string;
  core_signing_public_key: string;
  scope?: "skill_source.manage";
  expires_at: number;
  one_time_code: string;
}

export interface CallerReceiptView {
  request_id: string;
  device_id: string;
  operation: "list" | "add" | "remove";
  payload_hash: string;
  state: "in_progress" | "awaiting_approval" | "completed" | "failed" | "unconfirmed";
  http_status: number;
  result?: Record<string, unknown> | null;
  approval_id?: string | null;
  action_hash?: string | null;
  error_code?: string | null;
}

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface ProtocolNegotiation {
  protocol_version: "caller-pairing.v1";
  schema_digest: string;
  min_client_version: "caller-pairing.v1";
  capabilities: Array<string>;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

type OperationParameter = { name: string; in: string; required: boolean; schema: Record<string, unknown> };
type OperationDefinition = {
  method: string; pathTemplate: string; parameters: readonly OperationParameter[];
  requestBody: Record<string, unknown> | null; mutuallyExclusive: readonly (readonly string[])[];
  responses: Record<string, Record<string, unknown>>;
};

const CALLER_PAIRING_OPERATIONS: Record<string, OperationDefinition> = {
  "createCallerChallenge": {
    "method": "POST",
    "pathTemplate": "/v1/local-callers/challenges",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CallerChallengeInput"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerPairingTicket"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listCallerDevices": {
    "method": "GET",
    "pathTemplate": "/v1/local-callers/devices",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerDeviceList"
            }
          }
        }
      }
    }
  },
  "revokeCallerDevice": {
    "method": "POST",
    "pathTemplate": "/v1/local-callers/devices/{device_id}/revoke",
    "parameters": [
      {
        "name": "device_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Device Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerDeviceList"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "pairLocalCaller": {
    "method": "POST",
    "pathTemplate": "/v1/local-callers/pair",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CallerPairRequest"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerEncryptedReply"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "executeCallerCommand": {
    "method": "POST",
    "pathTemplate": "/v1/local-callers/commands",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CallerCommand"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerEncryptedReply"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "readCallerRequest": {
    "method": "POST",
    "pathTemplate": "/v1/local-callers/requests/readback",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CallerCommand"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerEncryptedReply"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getCallerRequest": {
    "method": "GET",
    "pathTemplate": "/v1/local-callers/requests/result",
    "parameters": [
      {
        "name": "device_id",
        "in": "query",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Device Id"
        }
      },
      {
        "name": "request_id",
        "in": "query",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Request Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CallerReceiptView"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "negotiateProtocol": {
    "method": "GET",
    "pathTemplate": "/v1/protocol/caller-pairing",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProtocolNegotiation"
            }
          }
        }
      }
    }
  }
} as const;

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface CallerPairingRequestOptions { idempotencyKey?: string; }
export interface CreateCallerChallengeOptions {
  idempotencyKey?: string;
}

export interface RevokeCallerDeviceOptions {
  idempotencyKey?: string;
}

export interface PairLocalCallerOptions {
  idempotencyKey?: string;
}

export interface ExecuteCallerCommandOptions {
  idempotencyKey?: string;
}

export interface ReadCallerRequestOptions {
  idempotencyKey?: string;
}

export interface GetCallerRequestOptions {
  deviceId: string;
  requestId: string;
}

export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only a bounded recent window per resource and stream scope. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly order = new Map<string, string[]>();
  private readonly latest = new Map<string, Cursor>();
  private readonly scopeOrder: string[] = [];
  constructor(private readonly maxSeenPerScope = 1024, private readonly maxScopes = 1024) {
    if (!Number.isSafeInteger(maxSeenPerScope) || maxSeenPerScope < 1 || !Number.isSafeInteger(maxScopes) || maxScopes < 1) throw new RangeError('cursor tracker bounds must be positive safe integers');
  }

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const parsed = parseCursor(frame.id);
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = BigInt(parsed).toString();
    const scope = this.seen.get(key) ?? new Set<string>();
    const order = this.order.get(key) ?? [];
    if (!this.seen.has(key)) { this.scopeOrder.push(key); while (this.scopeOrder.length > this.maxScopes) { const evictedKey = this.scopeOrder.shift(); if (evictedKey !== undefined) { this.seen.delete(evictedKey); this.order.delete(evictedKey); this.latest.delete(evictedKey); } } }
    if (scope.has(cursor)) return false;
    scope.add(cursor); order.push(cursor);
    while (order.length > this.maxSeenPerScope) { const evicted = order.shift(); if (evicted !== undefined) scope.delete(evicted); }
    this.seen.set(key, scope); this.order.set(key, order);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(parsed) > BigInt(previous)) this.latest.set(key, parsed);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    if (!scope || !streamKind) throw new TypeError('SSE scope is required');
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends CallerPairingError {
  constructor(message: string) { super('protocol_incompatible', message, false, 'refresh_and_retry'); this.name = 'ProtocolNegotiationError'; }
}

function validateProtocolNegotiation(value: unknown): ProtocolNegotiation {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new ProtocolNegotiationError('protocol response is not an object');
  const metadata = value as Record<string, unknown>;
  const required = ['protocol_version', 'schema_digest', 'min_client_version', 'capabilities'];
  if (required.some(field => !Object.prototype.hasOwnProperty.call(metadata, field))) throw new ProtocolNegotiationError('protocol response is missing required metadata');
  if (metadata.protocol_version !== CALLER_PAIRING_PROTOCOL_VERSION || metadata.min_client_version !== CALLER_PAIRING_PROTOCOL_VERSION) throw new ProtocolNegotiationError(`unsupported Core protocol: ${String(metadata.protocol_version)}`);
  if (metadata.schema_digest !== CALLER_PAIRING_SCHEMA_DIGEST) throw new ProtocolNegotiationError(`Core Schema digest mismatch: expected ${CALLER_PAIRING_SCHEMA_DIGEST}, got ${String(metadata.schema_digest)}`);
  if (!Array.isArray(metadata.capabilities) || metadata.capabilities.some(item => typeof item !== 'string' || item.length === 0)) throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
  return metadata as unknown as ProtocolNegotiation;
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues === 'function') {
    const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  throw new CallerPairingError('crypto_unavailable', 'Secure idempotency key generation is unavailable', false, 'none');
}

function requireIdempotencyKey(value: string): string {
  if (typeof value !== 'string' || !value) throw new TypeError('idempotencyKey must not be empty');
  return value;
}

function requireOption<T>(value: T | undefined, label: string): T {
  if (value === undefined || value === null) throw new TypeError(`${label} is required`);
  return value;
}


function pathPart(value: string, label: string): string {
  if (!value) throw new TypeError(`${label} must not be empty`);
  return encodeURIComponent(value);
}

function validateMutuallyExclusive(request: unknown, groups: readonly (readonly string[])[]): void {
  if (groups.length === 0) return;
  if (typeof request !== 'object' || request === null || Array.isArray(request)) throw new TypeError('request body must be an object');
  const record = request as Record<string, unknown>;
  for (const group of groups) {
    if (!Array.isArray(group) || group.length < 2 || group.some(field => typeof field !== 'string' || field.length === 0)) throw new TypeError('invalid mutually-exclusive schema metadata');
    const provided = group.filter(field => record[field] !== undefined && record[field] !== null);
    if (provided.length !== 1) throw new TypeError(`exactly one of ${group.join(', ')} is required`);
  }
}

export class CallerPairingClient {
  readonly protocolVersion = CALLER_PAIRING_PROTOCOL_VERSION;
  readonly schemaDigest = CALLER_PAIRING_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: CallerPairingTransport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(baseUrl = 'http://127.0.0.1:8000', transport: CallerPairingTransport = fetchCallerPairingTransport, clientVersion = CALLER_PAIRING_PROTOCOL_VERSION) {
    this.baseUrl = baseUrl.replace(/\/+$/, ''); this.transport = transport; this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS.negotiateProtocol, {}, true);
    const metadata = validateProtocolNegotiation(await readJson<unknown>(response));
    this.negotiated = metadata; return metadata;
  }

  private async requestOperation(operation: OperationDefinition, args: { pathParams?: Record<string, string>; query?: Record<string, string | undefined>; headers?: Record<string, string | undefined>; body?: string; bodyValue?: unknown; }, skipNegotiation = false): Promise<CallerPairingResponse> {
    validateMutuallyExclusive(args.bodyValue, operation.mutuallyExclusive);
    const path = operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, name: string) => { const value = args.pathParams?.[name]; if (value === undefined) throw new TypeError(`missing path parameter: ${name}`); return value; });
    const headers = Object.fromEntries(Object.entries(args.headers ?? {}).filter((entry): entry is [string, string] => entry[1] !== undefined));
    return this.requestRaw({ method: operation.method, path, query: args.query, headers, body: args.body }, skipNegotiation);
  }

  private async requestRaw(request: Omit<CallerPairingRequest, 'url'> & { path: string; query?: Record<string, string | undefined>; }, skipNegotiation = false): Promise<CallerPairingResponse> {
    if (!skipNegotiation) await this.negotiateProtocol();
    const url = new URL(`${this.baseUrl}${request.path}`); for (const [key, value] of Object.entries(request.query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    let response: CallerPairingResponse;
    try { response = await this.transport({ ...request, url: url.toString(), headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) } }); }
    catch (error: unknown) { if (error instanceof CallerPairingError) throw error; throw new CallerPairingError('transport_unavailable', error instanceof Error ? error.message : 'transport request failed', true, 'retry_later'); }
    const headers = responseHeaders(response.headers); this.responseMetadata = { status: response.status, idempotencyKey: headers['idempotency-key'], idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true' };
    if (response.status < 200 || response.status >= 300) throw await CallerPairingError.fromResponse(response); return response;
  }

  async createCallerChallenge(request: CallerChallengeInput, options: CreateCallerChallengeOptions = {}): Promise<CallerPairingTicket> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["createCallerChallenge"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<CallerPairingTicket>(response);
  }

  async listCallerDevices(): Promise<CallerDeviceList> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["listCallerDevices"], { headers: { Accept: "application/json" } });
    return readJson<CallerDeviceList>(response);
  }

  async revokeCallerDevice(deviceId: string, options: RevokeCallerDeviceOptions = {}): Promise<CallerDeviceList> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["revokeCallerDevice"], { pathParams: { "device_id": pathPart(deviceId, "device_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<CallerDeviceList>(response);
  }

  async pairLocalCaller(request: CallerPairRequest, options: PairLocalCallerOptions = {}): Promise<CallerEncryptedReply> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["pairLocalCaller"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<CallerEncryptedReply>(response);
  }

  async executeCallerCommand(request: CallerCommand, options: ExecuteCallerCommandOptions = {}): Promise<CallerEncryptedReply> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["executeCallerCommand"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<CallerEncryptedReply>(response);
  }

  async readCallerRequest(request: CallerCommand, options: ReadCallerRequestOptions = {}): Promise<CallerEncryptedReply> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["readCallerRequest"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<CallerEncryptedReply>(response);
  }

  async getCallerRequest(options: GetCallerRequestOptions): Promise<CallerReceiptView> {
    const response = await this.requestOperation(CALLER_PAIRING_OPERATIONS["getCallerRequest"], { query: { "device_id": String(requireOption(options.deviceId, 'device_id')), "request_id": String(requireOption(options.requestId, 'request_id')) }, headers: { Accept: "application/json" } });
    return readJson<CallerReceiptView>(response);
  }

}

export { CallerPairingError };
