/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-onboarding.openapi.json
// Generated by sdk/protocol/generate_onboarding.py; schema digest: aae5c5d98b0fda75c68fae94307b81db81df8e8a486a8eece40c0cbe60a5ccdc

import {
  OnboardingError,
  OnboardingRequest,
  OnboardingResponse,
  OnboardingTransport,
  fetchOnboardingTransport,
  parseCursor,
  readJson,
  responseHeaders,
  stringifyJson,
} from './onboarding-transport';

export const ONBOARDING_PROTOCOL_VERSION = "onboarding.v1" as const;
export const ONBOARDING_SCHEMA_DIGEST = "aae5c5d98b0fda75c68fae94307b81db81df8e8a486a8eece40c0cbe60a5ccdc" as const;
export const ONBOARDING_MAX_CURSOR = 9223372036854775807n;

/** All int64 values remain a safe number or a bigint; JSON parsing promotes large tokens. */
export type Int64 = number | bigint;
export type Cursor = Int64;

export interface CollaborationStart {
  template_id?: string;
  workspace_id?: string | null;
  task: string;
}

export interface CollaborationStarted {
  workflow_definition_id: string;
  graph_run_id: string;
  team_run_id?: string | null;
  status: string;
}

export interface CollaborationTemplateList {
  items: Array<CollaborationTemplateView>;
}

export interface CollaborationTemplateView {
  template_id: string;
  name: string;
  description: string;
  member_count: number;
}

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface ConnectionCreate {
  provider?: "openai-compatible" | "chatgpt" | "gemini";
  name?: string | null;
  base_url?: string | null;
  api_key?: string | null;
  project_id?: string | null;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface ConnectionDeleted {
  connection_id: string;
  disconnected?: boolean;
}

export interface ConnectionModelSelection {
  model_id: string;
  name?: string | null;
}

export interface ConnectionModels {
  connection_id: string;
  model_ids: Array<string>;
  model_names?: Record<string, unknown>;
}

export interface ConnectionProfile {
  connection_id: string;
  model_profile_id: string;
  model_id: string;
}

export interface ConversationInitialization {
  thread_id: string;
  session_id: string;
  workspace_id: string;
  title: string;
}

export interface ConversationLocalControlOpen {
  plugin_id: "operant.chrome.browser" | "operant.macos.computer";
  computer_bundle_id?: string | null;
}

export interface ConversationLocalControlSession {
  session_id: string;
  plugin_id: "operant.chrome.browser" | "operant.macos.computer";
  target_id: string;
  computer_bundle_id?: string | null;
  allowed_targets: Array<string>;
  state: "active" | "human_control" | "closed" | "failed";
  last_error?: string | null;
}

export interface ConversationLocalControlSessionList {
  items: Array<ConversationLocalControlSession>;
}

export interface ConversationMetadata {
  thread_id: string;
  title: string;
  title_source: "manual" | "auto" | "default";
  revision: number;
}

export interface ConversationMetadataList {
  items: Array<ConversationMetadata>;
}

export interface ConversationRename {
  title: string;
  expected_revision?: number | null;
}

export interface ConversationStart {
  workspace_id?: string | null;
  thread_id?: string | null;
  role_id?: string | null;
  model_profile_id?: string | null;
  title?: string | null;
  local_control_session_ids?: Array<string>;
}

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface LocalApplication {
  bundle_id: string;
  name: string;
}

export interface LocalApplicationList {
  items: Array<LocalApplication>;
}

export interface ModelOption {
  id: string;
  name: string;
  model_id: string;
}

export interface OAuthAttempt {
  attempt_id: string;
  connection_id: string;
  provider: "chatgpt" | "gemini";
  status: "pending" | "connected" | "ready" | "cancelled" | "expired" | "error";
  authorization_url?: string | null;
  message?: string | null;
  expires_at: string;
}

export interface OAuthStart {
  provider: "chatgpt" | "gemini";
  connection_id?: string | null;
  project_id?: string | null;
  client_id?: string | null;
  client_secret?: string | null;
}

export interface ProtocolNegotiation {
  protocol_version: "onboarding.v1";
  schema_digest: string;
  min_client_version: "onboarding.v1";
  capabilities: Array<string>;
}

export interface ProviderConnection {
  connection_id: string;
  name: string;
  provider: "openai-compatible" | "chatgpt" | "gemini";
  auth_method: "api_key" | "oauth";
  status: "needs_auth" | "connected" | "ready" | "error";
  base_url: string;
  model_ids?: Array<string>;
  model_names?: Record<string, unknown>;
  profile_ids?: Array<string>;
  account_label?: string | null;
  project_id?: string | null;
  error?: string | null;
}

export interface ProviderConnectionList {
  items: Array<ProviderConnection>;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export interface RoleOption {
  id: string;
  name: string;
  model_profile_id: string;
}

export interface SetupBootstrap {
  model_profile_id?: string | null;
}

export interface SetupState {
  ready: boolean;
  default_workspace_id?: string | null;
  default_model_profile_id?: string | null;
  default_role_id?: string | null;
  missing_steps?: Array<string>;
  connections?: Array<ProviderConnection>;
  roles?: Array<RoleOption>;
  models?: Array<ModelOption>;
}

export interface SkillSourceInput {
  path: string;
}

export interface SkillSourceList {
  items: Array<SkillSourceView>;
}

export interface SkillSourceView {
  root_ref: string;
  path: string;
  label: string;
  exists: boolean;
  enabled: boolean;
  issue?: string | null;
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

type OperationParameter = { name: string; in: string; required: boolean; schema: Record<string, unknown> };
type OperationDefinition = {
  method: string; pathTemplate: string; parameters: readonly OperationParameter[];
  requestBody: Record<string, unknown> | null; mutuallyExclusive: readonly (readonly string[])[];
  responses: Record<string, Record<string, unknown>>;
};

const ONBOARDING_OPERATIONS: Record<string, OperationDefinition> = {
  "listModelConnections": {
    "method": "GET",
    "pathTemplate": "/v1/setup/connections",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProviderConnectionList"
            }
          }
        }
      }
    }
  },
  "createModelConnection": {
    "method": "POST",
    "pathTemplate": "/v1/setup/connections",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConnectionCreate"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "201": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProviderConnection"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "discoverConnectionModels": {
    "method": "POST",
    "pathTemplate": "/v1/setup/connections/{connection_id}/models",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Connection Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConnectionModels"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "selectConnectionModel": {
    "method": "POST",
    "pathTemplate": "/v1/setup/connections/{connection_id}/profiles",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Connection Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConnectionModelSelection"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConnectionProfile"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "deleteModelConnection": {
    "method": "DELETE",
    "pathTemplate": "/v1/setup/connections/{connection_id}",
    "parameters": [
      {
        "name": "connection_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Connection Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConnectionDeleted"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "startModelOAuth": {
    "method": "POST",
    "pathTemplate": "/v1/setup/oauth/start",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/OAuthStart"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/OAuthAttempt"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getModelOAuthStatus": {
    "method": "GET",
    "pathTemplate": "/v1/setup/oauth/{attempt_id}",
    "parameters": [
      {
        "name": "attempt_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Attempt Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/OAuthAttempt"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "cancelModelOAuth": {
    "method": "DELETE",
    "pathTemplate": "/v1/setup/oauth/{attempt_id}",
    "parameters": [
      {
        "name": "attempt_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Attempt Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/OAuthAttempt"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listSkillSources": {
    "method": "GET",
    "pathTemplate": "/v1/setup/skill-sources",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SkillSourceList"
            }
          }
        }
      }
    }
  },
  "addSkillSource": {
    "method": "POST",
    "pathTemplate": "/v1/setup/skill-sources",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/SkillSourceInput"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SkillSourceView"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "removeSkillSource": {
    "method": "DELETE",
    "pathTemplate": "/v1/setup/skill-sources/{root_ref}",
    "parameters": [
      {
        "name": "root_ref",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Root Ref"
        }
      },
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SkillSourceList"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "openConversationLocalControl": {
    "method": "POST",
    "pathTemplate": "/v1/setup/local-control/sessions",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConversationLocalControlOpen"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationLocalControlSession"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listConversationLocalControlSessions": {
    "method": "GET",
    "pathTemplate": "/v1/setup/local-control/sessions",
    "parameters": [
      {
        "name": "request_id",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Request Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationLocalControlSessionList"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getSetupState": {
    "method": "GET",
    "pathTemplate": "/v1/setup/state",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SetupState"
            }
          }
        }
      }
    }
  },
  "bootstrapSetup": {
    "method": "POST",
    "pathTemplate": "/v1/setup/bootstrap",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/SetupBootstrap"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/SetupState"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "initializeConversation": {
    "method": "POST",
    "pathTemplate": "/v1/setup/conversations",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConversationStart"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationInitialization"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listConversationMetadata": {
    "method": "GET",
    "pathTemplate": "/v1/setup/conversations/metadata",
    "parameters": [
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 100,
          "title": "Limit"
        }
      },
      {
        "name": "request_id",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Request Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationMetadataList"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getConversationMetadata": {
    "method": "GET",
    "pathTemplate": "/v1/setup/conversations/{thread_id}/metadata",
    "parameters": [
      {
        "name": "thread_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Thread Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationMetadata"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "renameConversation": {
    "method": "PATCH",
    "pathTemplate": "/v1/setup/conversations/{thread_id}/metadata",
    "parameters": [
      {
        "name": "thread_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Thread Id"
        }
      },
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConversationRename"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ConversationMetadata"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listTeamTemplates": {
    "method": "GET",
    "pathTemplate": "/v1/setup/team-templates",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CollaborationTemplateList"
            }
          }
        }
      }
    }
  },
  "startTemplateTeam": {
    "method": "POST",
    "pathTemplate": "/v1/setup/teams/start",
    "parameters": [
      {
        "name": "idempotency-key",
        "in": "header",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "type": "string",
              "minLength": 1,
              "maxLength": 300
            },
            {
              "type": "null"
            }
          ],
          "title": "Idempotency-Key"
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/CollaborationStart"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "202": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/CollaborationStarted"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listLocalApplications": {
    "method": "GET",
    "pathTemplate": "/v1/setup/local-apps",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/LocalApplicationList"
            }
          }
        }
      }
    }
  },
  "negotiateProtocol": {
    "method": "GET",
    "pathTemplate": "/v1/protocol/onboarding",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/ProtocolNegotiation"
            }
          }
        }
      }
    }
  }
} as const;

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface OnboardingRequestOptions { idempotencyKey?: string; }
export interface CreateModelConnectionOptions {
  idempotencyKey?: string;
}

export interface DiscoverConnectionModelsOptions {
  idempotencyKey?: string;
}

export interface SelectConnectionModelOptions {
  idempotencyKey?: string;
}

export interface DeleteModelConnectionOptions {
  idempotencyKey?: string;
}

export interface StartModelOAuthOptions {
  idempotencyKey?: string;
}

export interface CancelModelOAuthOptions {
  idempotencyKey?: string;
}

export interface AddSkillSourceOptions {
  idempotencyKey?: string;
}

export interface RemoveSkillSourceOptions {
  idempotencyKey?: string;
}

export interface OpenConversationLocalControlOptions {
  idempotencyKey?: string;
}

export interface ListConversationLocalControlSessionsOptions {
  requestId?: string | null;
}

export interface BootstrapSetupOptions {
  idempotencyKey?: string;
}

export interface InitializeConversationOptions {
  idempotencyKey?: string;
}

export interface ListConversationMetadataOptions {
  limit?: number;
  requestId?: string | null;
}

export interface RenameConversationOptions {
  idempotencyKey?: string;
}

export interface StartTemplateTeamOptions {
  idempotencyKey?: string;
}

export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only a bounded recent window per resource and stream scope. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly order = new Map<string, string[]>();
  private readonly latest = new Map<string, Cursor>();
  private readonly scopeOrder: string[] = [];
  constructor(private readonly maxSeenPerScope = 1024, private readonly maxScopes = 1024) {
    if (!Number.isSafeInteger(maxSeenPerScope) || maxSeenPerScope < 1 || !Number.isSafeInteger(maxScopes) || maxScopes < 1) throw new RangeError('cursor tracker bounds must be positive safe integers');
  }

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const parsed = parseCursor(frame.id);
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = BigInt(parsed).toString();
    const scope = this.seen.get(key) ?? new Set<string>();
    const order = this.order.get(key) ?? [];
    if (!this.seen.has(key)) { this.scopeOrder.push(key); while (this.scopeOrder.length > this.maxScopes) { const evictedKey = this.scopeOrder.shift(); if (evictedKey !== undefined) { this.seen.delete(evictedKey); this.order.delete(evictedKey); this.latest.delete(evictedKey); } } }
    if (scope.has(cursor)) return false;
    scope.add(cursor); order.push(cursor);
    while (order.length > this.maxSeenPerScope) { const evicted = order.shift(); if (evicted !== undefined) scope.delete(evicted); }
    this.seen.set(key, scope); this.order.set(key, order);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(parsed) > BigInt(previous)) this.latest.set(key, parsed);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    if (!scope || !streamKind) throw new TypeError('SSE scope is required');
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends OnboardingError {
  constructor(message: string) { super('protocol_incompatible', message, false, 'refresh_and_retry'); this.name = 'ProtocolNegotiationError'; }
}

function validateProtocolNegotiation(value: unknown): ProtocolNegotiation {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new ProtocolNegotiationError('protocol response is not an object');
  const metadata = value as Record<string, unknown>;
  const required = ['protocol_version', 'schema_digest', 'min_client_version', 'capabilities'];
  if (required.some(field => !Object.prototype.hasOwnProperty.call(metadata, field))) throw new ProtocolNegotiationError('protocol response is missing required metadata');
  if (metadata.protocol_version !== ONBOARDING_PROTOCOL_VERSION || metadata.min_client_version !== ONBOARDING_PROTOCOL_VERSION) throw new ProtocolNegotiationError(`unsupported Core protocol: ${String(metadata.protocol_version)}`);
  if (metadata.schema_digest !== ONBOARDING_SCHEMA_DIGEST) throw new ProtocolNegotiationError(`Core Schema digest mismatch: expected ${ONBOARDING_SCHEMA_DIGEST}, got ${String(metadata.schema_digest)}`);
  if (!Array.isArray(metadata.capabilities) || metadata.capabilities.some(item => typeof item !== 'string' || item.length === 0)) throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
  return metadata as unknown as ProtocolNegotiation;
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues === 'function') {
    const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  throw new OnboardingError('crypto_unavailable', 'Secure idempotency key generation is unavailable', false, 'none');
}

function requireIdempotencyKey(value: string): string {
  if (typeof value !== 'string' || !value) throw new TypeError('idempotencyKey must not be empty');
  return value;
}


function pathPart(value: string, label: string): string {
  if (!value) throw new TypeError(`${label} must not be empty`);
  return encodeURIComponent(value);
}

function validateMutuallyExclusive(request: unknown, groups: readonly (readonly string[])[]): void {
  if (groups.length === 0) return;
  if (typeof request !== 'object' || request === null || Array.isArray(request)) throw new TypeError('request body must be an object');
  const record = request as Record<string, unknown>;
  for (const group of groups) {
    if (!Array.isArray(group) || group.length < 2 || group.some(field => typeof field !== 'string' || field.length === 0)) throw new TypeError('invalid mutually-exclusive schema metadata');
    const provided = group.filter(field => record[field] !== undefined && record[field] !== null);
    if (provided.length !== 1) throw new TypeError(`exactly one of ${group.join(', ')} is required`);
  }
}

export class OnboardingClient {
  readonly protocolVersion = ONBOARDING_PROTOCOL_VERSION;
  readonly schemaDigest = ONBOARDING_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: OnboardingTransport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(baseUrl = 'http://127.0.0.1:8000', transport: OnboardingTransport = fetchOnboardingTransport, clientVersion = ONBOARDING_PROTOCOL_VERSION) {
    this.baseUrl = baseUrl.replace(/\/+$/, ''); this.transport = transport; this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestOperation(ONBOARDING_OPERATIONS.negotiateProtocol, {}, true);
    const metadata = validateProtocolNegotiation(await readJson<unknown>(response));
    this.negotiated = metadata; return metadata;
  }

  private async requestOperation(operation: OperationDefinition, args: { pathParams?: Record<string, string>; query?: Record<string, string | undefined>; headers?: Record<string, string | undefined>; body?: string; bodyValue?: unknown; }, skipNegotiation = false): Promise<OnboardingResponse> {
    validateMutuallyExclusive(args.bodyValue, operation.mutuallyExclusive);
    const path = operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, name: string) => { const value = args.pathParams?.[name]; if (value === undefined) throw new TypeError(`missing path parameter: ${name}`); return value; });
    const headers = Object.fromEntries(Object.entries(args.headers ?? {}).filter((entry): entry is [string, string] => entry[1] !== undefined));
    return this.requestRaw({ method: operation.method, path, query: args.query, headers, body: args.body }, skipNegotiation);
  }

  private async requestRaw(request: Omit<OnboardingRequest, 'url'> & { path: string; query?: Record<string, string | undefined>; }, skipNegotiation = false): Promise<OnboardingResponse> {
    if (!skipNegotiation) await this.negotiateProtocol();
    const url = new URL(`${this.baseUrl}${request.path}`); for (const [key, value] of Object.entries(request.query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    let response: OnboardingResponse;
    try { response = await this.transport({ ...request, url: url.toString(), headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) } }); }
    catch (error: unknown) { if (error instanceof OnboardingError) throw error; throw new OnboardingError('transport_unavailable', error instanceof Error ? error.message : 'transport request failed', true, 'retry_later'); }
    const headers = responseHeaders(response.headers); this.responseMetadata = { status: response.status, idempotencyKey: headers['idempotency-key'], idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true' };
    if (response.status < 200 || response.status >= 300) throw await OnboardingError.fromResponse(response); return response;
  }

  async listModelConnections(): Promise<ProviderConnectionList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listModelConnections"], { headers: { Accept: "application/json" } });
    return readJson<ProviderConnectionList>(response);
  }

  async createModelConnection(request: ConnectionCreate, options: CreateModelConnectionOptions = {}): Promise<ProviderConnection> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["createModelConnection"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<ProviderConnection>(response);
  }

  async discoverConnectionModels(connectionId: string, options: DiscoverConnectionModelsOptions = {}): Promise<ConnectionModels> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["discoverConnectionModels"], { pathParams: { "connection_id": pathPart(connectionId, "connection_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<ConnectionModels>(response);
  }

  async selectConnectionModel(connectionId: string, request: ConnectionModelSelection, options: SelectConnectionModelOptions = {}): Promise<ConnectionProfile> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["selectConnectionModel"], { pathParams: { "connection_id": pathPart(connectionId, "connection_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<ConnectionProfile>(response);
  }

  async deleteModelConnection(connectionId: string, options: DeleteModelConnectionOptions = {}): Promise<ConnectionDeleted> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["deleteModelConnection"], { pathParams: { "connection_id": pathPart(connectionId, "connection_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<ConnectionDeleted>(response);
  }

  async startModelOAuth(request: OAuthStart, options: StartModelOAuthOptions = {}): Promise<OAuthAttempt> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["startModelOAuth"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<OAuthAttempt>(response);
  }

  async getModelOAuthStatus(attemptId: string): Promise<OAuthAttempt> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["getModelOAuthStatus"], { pathParams: { "attempt_id": pathPart(attemptId, "attempt_id") }, headers: { Accept: "application/json" } });
    return readJson<OAuthAttempt>(response);
  }

  async cancelModelOAuth(attemptId: string, options: CancelModelOAuthOptions = {}): Promise<OAuthAttempt> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["cancelModelOAuth"], { pathParams: { "attempt_id": pathPart(attemptId, "attempt_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<OAuthAttempt>(response);
  }

  async listSkillSources(): Promise<SkillSourceList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listSkillSources"], { headers: { Accept: "application/json" } });
    return readJson<SkillSourceList>(response);
  }

  async addSkillSource(request: SkillSourceInput, options: AddSkillSourceOptions = {}): Promise<SkillSourceView> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["addSkillSource"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<SkillSourceView>(response);
  }

  async removeSkillSource(rootRef: string, options: RemoveSkillSourceOptions = {}): Promise<SkillSourceList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["removeSkillSource"], { pathParams: { "root_ref": pathPart(rootRef, "root_ref") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<SkillSourceList>(response);
  }

  async openConversationLocalControl(request: ConversationLocalControlOpen, options: OpenConversationLocalControlOptions = {}): Promise<ConversationLocalControlSession> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["openConversationLocalControl"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<ConversationLocalControlSession>(response);
  }

  async listConversationLocalControlSessions(options: ListConversationLocalControlSessionsOptions = {}): Promise<ConversationLocalControlSessionList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listConversationLocalControlSessions"], { query: { "request_id": options.requestId === undefined ? undefined : String(options.requestId) }, headers: { Accept: "application/json" } });
    return readJson<ConversationLocalControlSessionList>(response);
  }

  async getSetupState(): Promise<SetupState> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["getSetupState"], { headers: { Accept: "application/json" } });
    return readJson<SetupState>(response);
  }

  async bootstrapSetup(request: SetupBootstrap, options: BootstrapSetupOptions = {}): Promise<SetupState> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["bootstrapSetup"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<SetupState>(response);
  }

  async initializeConversation(request: ConversationStart, options: InitializeConversationOptions = {}): Promise<ConversationInitialization> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["initializeConversation"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<ConversationInitialization>(response);
  }

  async listConversationMetadata(options: ListConversationMetadataOptions = {}): Promise<ConversationMetadataList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listConversationMetadata"], { query: { "limit": options.limit === undefined ? undefined : String(options.limit), "request_id": options.requestId === undefined ? undefined : String(options.requestId) }, headers: { Accept: "application/json" } });
    return readJson<ConversationMetadataList>(response);
  }

  async getConversationMetadata(threadId: string): Promise<ConversationMetadata> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["getConversationMetadata"], { pathParams: { "thread_id": pathPart(threadId, "thread_id") }, headers: { Accept: "application/json" } });
    return readJson<ConversationMetadata>(response);
  }

  async renameConversation(threadId: string, request: ConversationRename, options: RenameConversationOptions = {}): Promise<ConversationMetadata> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["renameConversation"], { pathParams: { "thread_id": pathPart(threadId, "thread_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<ConversationMetadata>(response);
  }

  async listTeamTemplates(): Promise<CollaborationTemplateList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listTeamTemplates"], { headers: { Accept: "application/json" } });
    return readJson<CollaborationTemplateList>(response);
  }

  async startTemplateTeam(request: CollaborationStart, options: StartTemplateTeamOptions = {}): Promise<CollaborationStarted> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["startTemplateTeam"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<CollaborationStarted>(response);
  }

  async listLocalApplications(): Promise<LocalApplicationList> {
    const response = await this.requestOperation(ONBOARDING_OPERATIONS["listLocalApplications"], { headers: { Accept: "application/json" } });
    return readJson<LocalApplicationList>(response);
  }

}

export { OnboardingError };
