/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-phase45.openapi.json
// Generated by sdk/protocol/generate_phase45.py; schema digest: 94a3b48ba9482184712c587937a9606373637663dd650d92fd252766e6e25af3

import {
  Phase45Error,
  Phase45Request,
  Phase45Response,
  Phase45Transport,
  fetchPhase45Transport,
  parseCursor,
  readJson,
  responseHeaders,
  stringifyJson,
} from './phase45-transport';

export const PHASE45_PROTOCOL_VERSION = "phase45.v1" as const;
export const PHASE45_SCHEMA_DIGEST = "94a3b48ba9482184712c587937a9606373637663dd650d92fd252766e6e25af3" as const;
export const PHASE45_MAX_CURSOR = 9223372036854775807n;

/** All int64 values remain a safe number or a bigint; JSON parsing promotes large tokens. */
export type Int64 = number | bigint;
export type Cursor = Int64;

export type Capability = "workspace.read" | "workspace.write" | "workspace.delete" | "process.exec" | "process.exec.no_network" | "network.egress" | "secret.use" | "git.commit" | "git.push" | "external.message.send" | "production.mutate" | "policy.modify";

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface ConsumeCapabilityBody {
  action_hash: string;
  capability: Capability;
}

export type DispatchIdempotency = "idempotent" | "non_idempotent";

export interface HTTPValidationError {
  detail?: Array<ValidationError>;
}

export interface IdempotentTriggerBody {
  idempotency_key: string;
}

export interface IssueCapabilityBody {
  action_hash: string;
  capability: Capability;
  issued_by: string;
  ttl_seconds?: number;
  max_uses?: number;
}

export type JsonValue = unknown;

export interface McpServerBody {
  server_id: string;
  transport: "stdio" | "legacy_sse";
  endpoint_ref?: string | null;
  secret_ref?: string | null;
  stdio_argv?: Array<string> | null;
  cwd_ref?: string | null;
  environment_refs?: Record<string, unknown>;
  workspace_root_ref?: string | null;
  docker_image?: string | null;
  allow_loopback_http?: boolean;
}

export interface McpToolCallBody {
  arguments?: Record<string, unknown>;
}

export type MisfirePolicy = "skip" | "fire_once" | "catch_up";

export interface NormalizeActionBody {
  principal: string;
  tool: string;
  operation: string;
  arguments?: Record<string, unknown>;
  requested_capabilities: Array<Capability>;
  idempotency_key: string;
  workspace?: string | null;
  workspace_id?: string | null;
  session_id?: string | null;
  workflow_run_id?: string | null;
  node_run_id?: string | null;
  agent_instance_id?: string | null;
  secret_refs?: Array<string>;
  data_classification?: string;
  sandbox_profile?: string;
  network_profile?: string;
  dry_run?: boolean;
}

export interface Phase45ApprovalDecisionBody {
  approved: boolean;
  reason_code?: string | null;
}

export interface PolicyTestBody {
  actions: Array<NormalizeActionBody>;
}

export interface ProtocolNegotiation {
  protocol_version: "phase45.v1";
  schema_digest: string;
  min_client_version: "phase45.v1";
  capabilities: Array<string>;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export type RunRequestStatus = "queued" | "leased" | "retry_wait" | "succeeded" | "cancelled" | "dead_letter" | "manual_reconcile_required";

export interface ScheduleDefinition {
  id?: string;
  version?: number;
  name: string;
  trigger_kind: TriggerKind;
  cron_expression?: string | null;
  timer_at?: string | null;
  timezone_name: string;
  misfire_policy?: MisfirePolicy;
  max_catch_up?: number;
  workflow_id: string;
  workflow_version: number;
  workflow_input?: Record<string, unknown>;
  concurrency_limit?: number;
  max_attempts?: number;
  retry_base_seconds?: number;
  retry_max_seconds?: number;
  dispatch_idempotency?: DispatchIdempotency;
  status?: ScheduleStatus;
  created_at?: string;
}

export type ScheduleStatus = "enabled" | "paused" | "cancelled";

export interface ScheduleStatusBody {
  status: ScheduleStatus;
  expected_version: number;
}

export interface SkillDiscoverBody {
  root_refs?: Array<string>;
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export type TriggerKind = "cron" | "timer";

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

type OperationParameter = { name: string; in: string; required: boolean; schema: Record<string, unknown> };
type OperationDefinition = {
  method: string; pathTemplate: string; parameters: readonly OperationParameter[];
  requestBody: Record<string, unknown> | null; mutuallyExclusive: readonly (readonly string[])[];
  responses: Record<string, Record<string, unknown>>;
};

const PHASE45_OPERATIONS: Record<string, OperationDefinition> = {
  "negotiateProtocol": {
    "method": "GET",
    "pathTemplate": "/v1/protocol/phase45",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {}
          }
        }
      }
    }
  },
  "normalizeAction": {
    "method": "POST",
    "pathTemplate": "/v1/security/actions/normalize",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/NormalizeActionBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Normalizeaction"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "checkPolicy": {
    "method": "POST",
    "pathTemplate": "/v1/security/policy/check",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/NormalizeActionBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Checkpolicy"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "explainPolicy": {
    "method": "POST",
    "pathTemplate": "/v1/security/policy/explain",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/NormalizeActionBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Explainpolicy"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "testPolicy": {
    "method": "POST",
    "pathTemplate": "/v1/security/policy/test",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/PolicyTestBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Testpolicy"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getPhase45Approval": {
    "method": "GET",
    "pathTemplate": "/v1/security/approvals/{approval_id}",
    "parameters": [
      {
        "name": "approval_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Approval Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Getphase45Approval"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "decidePhase45Approval": {
    "method": "POST",
    "pathTemplate": "/v1/security/approvals/{approval_id}",
    "parameters": [
      {
        "name": "approval_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Approval Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/Phase45ApprovalDecisionBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Decidephase45Approval"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "reviewPhase45Approval": {
    "method": "POST",
    "pathTemplate": "/v1/security/approvals/{approval_id}/review",
    "parameters": [
      {
        "name": "approval_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Approval Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Reviewphase45Approval"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "issueCapabilityLease": {
    "method": "POST",
    "pathTemplate": "/v1/security/capability-leases",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/IssueCapabilityBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Issuecapabilitylease"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "consumeCapabilityLease": {
    "method": "POST",
    "pathTemplate": "/v1/security/capability-leases/{lease_id}/consume",
    "parameters": [
      {
        "name": "lease_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Lease Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ConsumeCapabilityBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Consumecapabilitylease"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listSecurityAudit": {
    "method": "GET",
    "pathTemplate": "/v1/security/actions/{action_hash}/audit",
    "parameters": [
      {
        "name": "action_hash",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Action Hash"
        }
      },
      {
        "name": "after_cursor",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "minimum": 0,
          "default": 0,
          "title": "After Cursor"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 100,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listsecurityaudit"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "discoverSkills": {
    "method": "POST",
    "pathTemplate": "/v1/skills/discover",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/SkillDiscoverBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Discoverskills"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listSkills": {
    "method": "GET",
    "pathTemplate": "/v1/skills",
    "parameters": [
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 200,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listskills"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listMcpServers": {
    "method": "GET",
    "pathTemplate": "/v1/mcp/servers",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Listmcpservers"
            }
          }
        }
      }
    }
  },
  "createMcpServer": {
    "method": "POST",
    "pathTemplate": "/v1/mcp/servers",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/McpServerBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "201": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Createmcpserver"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "updateMcpServer": {
    "method": "PUT",
    "pathTemplate": "/v1/mcp/servers/{server_id}",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/McpServerBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Updatemcpserver"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "deleteMcpServer": {
    "method": "DELETE",
    "pathTemplate": "/v1/mcp/servers/{server_id}",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "boolean"
              },
              "title": "Response Deletemcpserver"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listMcpWorkspaceRoots": {
    "method": "GET",
    "pathTemplate": "/v1/mcp/workspace-roots",
    "parameters": [],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "additionalProperties": true,
              "type": "object",
              "title": "Response Listmcpworkspaceroots"
            }
          }
        }
      }
    }
  },
  "listMcpTools": {
    "method": "GET",
    "pathTemplate": "/v1/mcp/servers/{server_id}/tools",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listmcptools"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getMcpActionReceipt": {
    "method": "GET",
    "pathTemplate": "/v1/mcp/action-receipts/{action_hash}",
    "parameters": [
      {
        "name": "action_hash",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Action Hash"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Getmcpactionreceipt"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "startMcpServer": {
    "method": "POST",
    "pathTemplate": "/v1/mcp/servers/{server_id}/start",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Startmcpserver"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "stopMcpServer": {
    "method": "POST",
    "pathTemplate": "/v1/mcp/servers/{server_id}/stop",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Stopmcpserver"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "callMcpTool": {
    "method": "POST",
    "pathTemplate": "/v1/mcp/servers/{server_id}/tools/{tool_name}/call",
    "parameters": [
      {
        "name": "server_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Server Id"
        }
      },
      {
        "name": "tool_name",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Tool Name"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/McpToolCallBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Callmcptool"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "createSchedule": {
    "method": "POST",
    "pathTemplate": "/v1/schedules",
    "parameters": [
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ScheduleDefinition"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "201": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Createschedule"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listSchedules": {
    "method": "GET",
    "pathTemplate": "/v1/schedules",
    "parameters": [
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 200,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listschedules"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "updateSchedule": {
    "method": "PUT",
    "pathTemplate": "/v1/schedules/{schedule_id}",
    "parameters": [
      {
        "name": "schedule_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Schedule Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ScheduleDefinition"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Updateschedule"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "getSchedule": {
    "method": "GET",
    "pathTemplate": "/v1/schedules/{schedule_id}",
    "parameters": [
      {
        "name": "schedule_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Schedule Id"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Getschedule"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "setScheduleStatus": {
    "method": "POST",
    "pathTemplate": "/v1/schedules/{schedule_id}/status",
    "parameters": [
      {
        "name": "schedule_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Schedule Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/ScheduleStatusBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Setschedulestatus"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "triggerSchedule": {
    "method": "POST",
    "pathTemplate": "/v1/schedules/{schedule_id}/trigger",
    "parameters": [
      {
        "name": "schedule_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Schedule Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/IdempotentTriggerBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Triggerschedule"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listSchedulerQueue": {
    "method": "GET",
    "pathTemplate": "/v1/scheduler/queue",
    "parameters": [
      {
        "name": "status",
        "in": "query",
        "required": false,
        "schema": {
          "anyOf": [
            {
              "$ref": "#/components/schemas/RunRequestStatus"
            },
            {
              "type": "null"
            }
          ],
          "title": "Status"
        }
      },
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 200,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listschedulerqueue"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "listDeadLetter": {
    "method": "GET",
    "pathTemplate": "/v1/scheduler/dead-letter",
    "parameters": [
      {
        "name": "limit",
        "in": "query",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 500,
          "minimum": 1,
          "default": 200,
          "title": "Limit"
        }
      }
    ],
    "requestBody": null,
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Listdeadletter"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  },
  "replayDeadLetter": {
    "method": "POST",
    "pathTemplate": "/v1/scheduler/dead-letter/{request_id}/replay",
    "parameters": [
      {
        "name": "request_id",
        "in": "path",
        "required": true,
        "schema": {
          "type": "string",
          "title": "Request Id"
        }
      },
      {
        "name": "Idempotency-Key",
        "in": "header",
        "required": false,
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 300
        }
      }
    ],
    "requestBody": {
      "required": true,
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/IdempotentTriggerBody"
          }
        }
      }
    },
    "mutuallyExclusive": [],
    "responses": {
      "200": {
        "description": "Successful Response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": true,
              "title": "Response Replaydeadletter"
            }
          }
        }
      },
      "422": {
        "description": "Validation Error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/HTTPValidationError"
            }
          }
        }
      }
    }
  }
} as const;

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface Phase45RequestOptions { idempotencyKey?: string; }
export interface NormalizeActionOptions {
  idempotencyKey?: string;
}

export interface CheckPolicyOptions {
  idempotencyKey?: string;
}

export interface ExplainPolicyOptions {
  idempotencyKey?: string;
}

export interface TestPolicyOptions {
  idempotencyKey?: string;
}

export interface DecidePhase45ApprovalOptions {
  idempotencyKey?: string;
}

export interface ReviewPhase45ApprovalOptions {
  idempotencyKey?: string;
}

export interface IssueCapabilityLeaseOptions {
  idempotencyKey?: string;
}

export interface ConsumeCapabilityLeaseOptions {
  idempotencyKey?: string;
}

export interface ListSecurityAuditOptions {
  afterCursor?: number;
  limit?: number;
}

export interface DiscoverSkillsOptions {
  idempotencyKey?: string;
}

export interface ListSkillsOptions {
  limit?: number;
}

export interface CreateMcpServerOptions {
  idempotencyKey?: string;
}

export interface UpdateMcpServerOptions {
  idempotencyKey?: string;
}

export interface DeleteMcpServerOptions {
  idempotencyKey?: string;
}

export interface StartMcpServerOptions {
  idempotencyKey?: string;
}

export interface StopMcpServerOptions {
  idempotencyKey?: string;
}

export interface CallMcpToolOptions {
  idempotencyKey?: string;
}

export interface CreateScheduleOptions {
  idempotencyKey?: string;
}

export interface ListSchedulesOptions {
  limit?: number;
}

export interface UpdateScheduleOptions {
  idempotencyKey?: string;
}

export interface SetScheduleStatusOptions {
  idempotencyKey?: string;
}

export interface TriggerScheduleOptions {
  idempotencyKey?: string;
}

export interface ListSchedulerQueueOptions {
  status?: RunRequestStatus | null;
  limit?: number;
}

export interface ListDeadLetterOptions {
  limit?: number;
}

export interface ReplayDeadLetterOptions {
  idempotencyKey?: string;
}

export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only a bounded recent window per resource and stream scope. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly order = new Map<string, string[]>();
  private readonly latest = new Map<string, Cursor>();
  private readonly scopeOrder: string[] = [];
  constructor(private readonly maxSeenPerScope = 1024, private readonly maxScopes = 1024) {
    if (!Number.isSafeInteger(maxSeenPerScope) || maxSeenPerScope < 1 || !Number.isSafeInteger(maxScopes) || maxScopes < 1) throw new RangeError('cursor tracker bounds must be positive safe integers');
  }

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const parsed = parseCursor(frame.id);
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = BigInt(parsed).toString();
    const scope = this.seen.get(key) ?? new Set<string>();
    const order = this.order.get(key) ?? [];
    if (!this.seen.has(key)) { this.scopeOrder.push(key); while (this.scopeOrder.length > this.maxScopes) { const evictedKey = this.scopeOrder.shift(); if (evictedKey !== undefined) { this.seen.delete(evictedKey); this.order.delete(evictedKey); this.latest.delete(evictedKey); } } }
    if (scope.has(cursor)) return false;
    scope.add(cursor); order.push(cursor);
    while (order.length > this.maxSeenPerScope) { const evicted = order.shift(); if (evicted !== undefined) scope.delete(evicted); }
    this.seen.set(key, scope); this.order.set(key, order);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(parsed) > BigInt(previous)) this.latest.set(key, parsed);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    if (!scope || !streamKind) throw new TypeError('SSE scope is required');
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends Phase45Error {
  constructor(message: string) { super('protocol_incompatible', message, false, 'refresh_and_retry'); this.name = 'ProtocolNegotiationError'; }
}

function validateProtocolNegotiation(value: unknown): ProtocolNegotiation {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new ProtocolNegotiationError('protocol response is not an object');
  const metadata = value as Record<string, unknown>;
  const required = ['protocol_version', 'schema_digest', 'min_client_version', 'capabilities'];
  if (required.some(field => !Object.prototype.hasOwnProperty.call(metadata, field))) throw new ProtocolNegotiationError('protocol response is missing required metadata');
  if (metadata.protocol_version !== PHASE45_PROTOCOL_VERSION || metadata.min_client_version !== PHASE45_PROTOCOL_VERSION) throw new ProtocolNegotiationError(`unsupported Core protocol: ${String(metadata.protocol_version)}`);
  if (metadata.schema_digest !== PHASE45_SCHEMA_DIGEST) throw new ProtocolNegotiationError(`Core Schema digest mismatch: expected ${PHASE45_SCHEMA_DIGEST}, got ${String(metadata.schema_digest)}`);
  if (!Array.isArray(metadata.capabilities) || metadata.capabilities.some(item => typeof item !== 'string' || item.length === 0)) throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
  return metadata as unknown as ProtocolNegotiation;
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (typeof cryptoApi?.randomUUID === 'function') return cryptoApi.randomUUID();
  if (typeof cryptoApi?.getRandomValues === 'function') {
    const bytes = cryptoApi.getRandomValues(new Uint8Array(16));
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes, byte => byte.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }
  throw new Phase45Error('crypto_unavailable', 'Secure idempotency key generation is unavailable', false, 'none');
}

function requireIdempotencyKey(value: string): string {
  if (typeof value !== 'string' || !value) throw new TypeError('idempotencyKey must not be empty');
  return value;
}


function pathPart(value: string | number, label: string): string {
  if (value === '' || !Number.isFinite(typeof value === 'number' ? value : 0)) throw new TypeError(`${label} must be a valid path value`);
  return encodeURIComponent(String(value));
}

function validateMutuallyExclusive(request: unknown, groups: readonly (readonly string[])[]): void {
  if (groups.length === 0) return;
  if (typeof request !== 'object' || request === null || Array.isArray(request)) throw new TypeError('request body must be an object');
  const record = request as Record<string, unknown>;
  for (const group of groups) {
    if (!Array.isArray(group) || group.length < 2 || group.some(field => typeof field !== 'string' || field.length === 0)) throw new TypeError('invalid mutually-exclusive schema metadata');
    const provided = group.filter(field => record[field] !== undefined && record[field] !== null);
    if (provided.length !== 1) throw new TypeError(`exactly one of ${group.join(', ')} is required`);
  }
}

export class Phase45Client {
  readonly protocolVersion = PHASE45_PROTOCOL_VERSION;
  readonly schemaDigest = PHASE45_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: Phase45Transport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(baseUrl = 'http://127.0.0.1:8000', transport: Phase45Transport = fetchPhase45Transport, clientVersion = PHASE45_PROTOCOL_VERSION) {
    this.baseUrl = baseUrl.replace(/\/+$/, ''); this.transport = transport; this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestOperation(PHASE45_OPERATIONS.negotiateProtocol, {}, true);
    const metadata = validateProtocolNegotiation(await readJson<unknown>(response));
    this.negotiated = metadata; return metadata;
  }

  private async requestOperation(operation: OperationDefinition, args: { pathParams?: Record<string, string>; query?: Record<string, string | undefined>; headers?: Record<string, string | undefined>; body?: string; bodyValue?: unknown; }, skipNegotiation = false): Promise<Phase45Response> {
    validateMutuallyExclusive(args.bodyValue, operation.mutuallyExclusive);
    const path = operation.pathTemplate.replace(/\{([^}]+)\}/g, (_match, name: string) => { const value = args.pathParams?.[name]; if (value === undefined) throw new TypeError(`missing path parameter: ${name}`); return value; });
    const headers = Object.fromEntries(Object.entries(args.headers ?? {}).filter((entry): entry is [string, string] => entry[1] !== undefined));
    return this.requestRaw({ method: operation.method, path, query: args.query, headers, body: args.body }, skipNegotiation);
  }

  private async requestRaw(request: Omit<Phase45Request, 'url'> & { path: string; query?: Record<string, string | undefined>; }, skipNegotiation = false): Promise<Phase45Response> {
    if (!skipNegotiation) await this.negotiateProtocol();
    const url = new URL(`${this.baseUrl}${request.path}`); for (const [key, value] of Object.entries(request.query ?? {})) if (value !== undefined) url.searchParams.set(key, value);
    let response: Phase45Response;
    try { response = await this.transport({ ...request, url: url.toString(), headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) } }); }
    catch (error: unknown) { if (error instanceof Phase45Error) throw error; throw new Phase45Error('transport_unavailable', error instanceof Error ? error.message : 'transport request failed', true, 'retry_later'); }
    const headers = responseHeaders(response.headers); this.responseMetadata = { status: response.status, idempotencyKey: headers['idempotency-key'], idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true' };
    if (response.status < 200 || response.status >= 300) throw await Phase45Error.fromResponse(response); return response;
  }

  async normalizeAction(request: NormalizeActionBody, options: NormalizeActionOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["normalizeAction"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async checkPolicy(request: NormalizeActionBody, options: CheckPolicyOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["checkPolicy"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async explainPolicy(request: NormalizeActionBody, options: ExplainPolicyOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["explainPolicy"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async testPolicy(request: PolicyTestBody, options: TestPolicyOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["testPolicy"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async getPhase45Approval(approvalId: string): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["getPhase45Approval"], { pathParams: { "approval_id": pathPart(approvalId, "approval_id") }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async decidePhase45Approval(approvalId: string, request: Phase45ApprovalDecisionBody, options: DecidePhase45ApprovalOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["decidePhase45Approval"], { pathParams: { "approval_id": pathPart(approvalId, "approval_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async reviewPhase45Approval(approvalId: string, options: ReviewPhase45ApprovalOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["reviewPhase45Approval"], { pathParams: { "approval_id": pathPart(approvalId, "approval_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async issueCapabilityLease(request: IssueCapabilityBody, options: IssueCapabilityLeaseOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["issueCapabilityLease"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async consumeCapabilityLease(leaseId: string, request: ConsumeCapabilityBody, options: ConsumeCapabilityLeaseOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["consumeCapabilityLease"], { pathParams: { "lease_id": pathPart(leaseId, "lease_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async listSecurityAudit(actionHash: string, options: ListSecurityAuditOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listSecurityAudit"], { pathParams: { "action_hash": pathPart(actionHash, "action_hash") }, query: { "after_cursor": options.afterCursor === undefined ? undefined : String(options.afterCursor), "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async discoverSkills(request: SkillDiscoverBody, options: DiscoverSkillsOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["discoverSkills"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async listSkills(options: ListSkillsOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listSkills"], { query: { "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async listMcpServers(): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listMcpServers"], { headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async createMcpServer(request: McpServerBody, options: CreateMcpServerOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["createMcpServer"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async updateMcpServer(serverId: string, request: McpServerBody, options: UpdateMcpServerOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["updateMcpServer"], { pathParams: { "server_id": pathPart(serverId, "server_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async deleteMcpServer(serverId: string, options: DeleteMcpServerOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["deleteMcpServer"], { pathParams: { "server_id": pathPart(serverId, "server_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async listMcpWorkspaceRoots(): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listMcpWorkspaceRoots"], { headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async listMcpTools(serverId: string): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listMcpTools"], { pathParams: { "server_id": pathPart(serverId, "server_id") }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async getMcpActionReceipt(actionHash: string): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["getMcpActionReceipt"], { pathParams: { "action_hash": pathPart(actionHash, "action_hash") }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async startMcpServer(serverId: string, options: StartMcpServerOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["startMcpServer"], { pathParams: { "server_id": pathPart(serverId, "server_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async stopMcpServer(serverId: string, options: StopMcpServerOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["stopMcpServer"], { pathParams: { "server_id": pathPart(serverId, "server_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async callMcpTool(serverId: string, toolName: string, request: McpToolCallBody, options: CallMcpToolOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["callMcpTool"], { pathParams: { "server_id": pathPart(serverId, "server_id"), "tool_name": pathPart(toolName, "tool_name") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async createSchedule(request: ScheduleDefinition, options: CreateScheduleOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["createSchedule"], { headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async listSchedules(options: ListSchedulesOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listSchedules"], { query: { "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async updateSchedule(scheduleId: string, request: ScheduleDefinition, options: UpdateScheduleOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["updateSchedule"], { pathParams: { "schedule_id": pathPart(scheduleId, "schedule_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async getSchedule(scheduleId: string): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["getSchedule"], { pathParams: { "schedule_id": pathPart(scheduleId, "schedule_id") }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async setScheduleStatus(scheduleId: string, request: ScheduleStatusBody, options: SetScheduleStatusOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["setScheduleStatus"], { pathParams: { "schedule_id": pathPart(scheduleId, "schedule_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async triggerSchedule(scheduleId: string, request: IdempotentTriggerBody, options: TriggerScheduleOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["triggerSchedule"], { pathParams: { "schedule_id": pathPart(scheduleId, "schedule_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

  async listSchedulerQueue(options: ListSchedulerQueueOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listSchedulerQueue"], { query: { "status": options.status === undefined ? undefined : String(options.status), "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async listDeadLetter(options: ListDeadLetterOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["listDeadLetter"], { query: { "limit": options.limit === undefined ? undefined : String(options.limit) }, headers: { Accept: "application/json" } });
    return readJson<Record<string, unknown>>(response);
  }

  async replayDeadLetter(requestId: string, request: IdempotentTriggerBody, options: ReplayDeadLetterOptions = {}): Promise<Record<string, unknown>> {
    const response = await this.requestOperation(PHASE45_OPERATIONS["replayDeadLetter"], { pathParams: { "request_id": pathPart(requestId, "request_id") }, headers: { 'Idempotency-Key': requireIdempotencyKey(options.idempotencyKey ?? newIdempotencyKey()), Accept: "application/json", 'Content-Type': "application/json" }, bodyValue: request, body: stringifyJson(request) });
    return readJson<Record<string, unknown>>(response);
  }

}

export { Phase45Error };
