/* eslint-disable */
// GENERATED FILE - DO NOT EDIT. Source: sdk/protocol/schema/operant-phase1e.openapi.json
// Generated by sdk/protocol/generate_phase1e.py; schema digest: 153edbae00f18d525bd5fb14f3551221fb7bd24a0cbbaa6b6c331a395d0af1b1

import {
  Phase1EError,
  Phase1ERequest,
  Phase1EResponse,
  Phase1ETransport,
  fetchPhase1ETransport,
  parseCursor,
  parseSse,
  readJson,
  readText,
  responseHeaders,
} from './phase1e-transport';

export const PHASE1E_PROTOCOL_VERSION = 'phase1e.v1' as const;
export const PHASE1E_SCHEMA_DIGEST = '153edbae00f18d525bd5fb14f3551221fb7bd24a0cbbaa6b6c331a395d0af1b1' as const;
export const PHASE1E_MAX_CURSOR = 9223372036854775807n;

/** Cursor is kept lossless for SSE ids beyond Number.MAX_SAFE_INTEGER. */
export type Cursor = number | bigint;

export interface ProtocolNegotiation {
  protocol_version: "phase1e.v1";
  schema_digest: string;
  min_client_version: "phase1e.v1";
  capabilities: Array<string>;
}

export type ErrorRecovery = "none" | "retry" | "retry_later" | "retry_same_idempotency_key" | "use_new_idempotency_key" | "refresh_and_retry" | "manual_reconcile";

export interface ErrorDescriptor {
  code: string;
  message: string;
  retryable: boolean;
  recovery: ErrorRecovery;
}

export interface ErrorEnvelope {
  detail: unknown;
  error: ErrorDescriptor;
  [key: string]: unknown;
}

export interface ReceiptResource {
  type: string;
  id: string;
}

export interface CommandReceipt {
  command_kind: "command" | "stream";
  accepted: boolean;
  command_id: string;
  stream_replay_available?: boolean;
  first_event_type?: string | null;
  resource_type?: string | null;
  resource_id?: string | null;
  replay_url?: string | null;
  replay_after_cursor?: Cursor | null;
  recovery?: "replay_events" | "not_available" | "none" | "manual_reconcile";
  resource?: ReceiptResource | null;
  [key: string]: unknown;
}

export interface ProjectThreadSummary {
  id: string;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectWorkflowRunSummary {
  id: string;
  status: string;
  current_stage: string;
  summary: string;
  created_at: string;
  updated_at: string;
}

export interface ProjectProjection {
  project_id: string;
  workspace_ref: string;
  readable: boolean;
  writable: boolean;
  created_at: string;
  threads: Array<ProjectThreadSummary>;
  workflow_runs: Array<ProjectWorkflowRunSummary>;
}

export interface WorkspaceFileEntry {
  path: string;
  name: string;
  type: "file" | "directory";
  size_bytes: number | null;
  modified_at: string | null;
}

export interface WorkspaceFilesPage {
  workspace_id: string;
  path: string;
  entries: Array<WorkspaceFileEntry>;
  snapshot: string;
  next_page_token: string | null;
}

export type ThreadStatus = "active" | "completed" | "cancelled" | "archived";

export interface ThreadLegacyRef {
  source_type: "session" | "workflow_run";
  source_id: string;
}

export interface ThreadProjection {
  id: string;
  cursor: Cursor | null;
  parent_thread_id: string | null;
  workspace_ref: string | null;
  status: ThreadStatus;
  legacy_refs: Array<ThreadLegacyRef>;
  created_at: string;
  updated_at: string;
  archived_at: string | null;
}

export interface RoleSnapshot {
  role_id: string;
  role_version: number;
  role_name: string;
  system_prompt: string;
  model_profile_id: string;
  model_profile_name: string;
  provider: string;
  model_id: string;
  base_url: string;
  secret_ref: string;
  context_window?: number | null;
  effort: string;
  provider_effort_parameter?: string | null;
  provider_effort_value?: string | null;
  tool_policy: Record<string, unknown>;
  budget: Record<string, unknown>;
  memory_scope: string;
  captured_at: string;
  overrides: Record<string, unknown>;
  [key: string]: unknown;
}

export interface Session {
  id: string;
  role_snapshot: RoleSnapshot;
  created_at: string;
}

export interface CreateRole {
  name: string;
  system_prompt: string;
  model_profile_id: string;
  [key: string]: unknown;
}

export interface CreateSessionRequest {
  role_id?: string | null;
  new_role?: CreateRole | null;
  model_profile_id?: string | null;
  effort?: string | null;
  budget_overrides?: Record<string, unknown> | null;
}

export interface ReferenceRequest {
  path?: string;
  start_line?: number;
  end_line?: number;
  [key: string]: unknown;
}

export interface RunSessionRequest {
  message: string;
  workspace: string;
  thread_id?: string | null;
  references?: Array<ReferenceRequest>;
}

export interface RuntimeEvent {
  id?: string;
  cursor?: Cursor | null;
  session_id?: string;
  agent_id?: string | null;
  event_type?: string;
  payload?: Record<string, unknown>;
  created_at?: string;
  [key: string]: unknown;
}

export interface SseFrame {
  id: Cursor | null;
  event: string;
  data: unknown;
  resource_scope?: string;
  stream_kind?: string;
}

export type ApprovalStatus = "pending" | "approved" | "rejected" | "expired";

export interface ApprovalProjection {
  approval_id: string;
  tool_call_id: string;
  category: string;
  detail: string;
  action_hash: string;
  status: ApprovalStatus;
  requested_at: string;
  expires_at: string;
  continuation_available: boolean;
}

export interface ApprovalDecisionRequest {
  approved: boolean;
}

export interface ApprovalDecisionResult {
  accepted: boolean;
  changed: boolean;
  approved: boolean;
  status: ApprovalStatus;
  approval_id: string;
  continuation_available: boolean;
  [key: string]: unknown;
}

export interface ResponseMetadata {
  status: number; idempotencyKey?: string; idempotencyReplayed: boolean;
}
export interface Phase1ERequestOptions { idempotencyKey?: string; }
export interface WorkspaceFilesOptions {
  path?: string; limit?: number; pageToken?: string; snapshot?: string; afterName?: string;
}
export interface ProjectListOptions { afterCursor?: Cursor; limit?: number; }
export interface ThreadListOptions {
  afterCursor?: Cursor; limit?: number; parentThreadId?: string;
  workspaceRef?: string; status?: ThreadStatus;
}
export interface RunSessionStreamOptions extends Phase1ERequestOptions {
  lastEventId?: Cursor;
}
export interface RunSessionStream {
  receipt: CommandReceipt | null; metadata: ResponseMetadata;
  events: AsyncIterable<SseFrame>;
}

/** Deduplicate only within the same resource and stream scope. Cursor gaps are valid. */
export class ScopedCursorTracker {
  private readonly seen = new Map<string, Set<string>>();
  private readonly latest = new Map<string, Cursor>();

  accept(frame: SseFrame): boolean {
    if (frame.id === null || frame.id === undefined) return true;
    if (!frame.resource_scope || !frame.stream_kind) throw new TypeError('SSE scope is required');
    const key = `${frame.resource_scope}\0${frame.stream_kind}`;
    const cursor = String(frame.id);
    const scope = this.seen.get(key) ?? new Set<string>();
    if (scope.has(cursor)) return false;
    scope.add(cursor);
    this.seen.set(key, scope);
    const previous = this.latest.get(key);
    if (previous === undefined || BigInt(frame.id) > BigInt(previous)) this.latest.set(key, frame.id);
    return true;
  }

  last(scope: string, streamKind: string): Cursor | null {
    return this.latest.get(`${scope}\0${streamKind}`) ?? null;
  }
}

export class ProtocolNegotiationError extends Error {
  constructor(message: string) { super(message); this.name = 'ProtocolNegotiationError'; }
}

function newIdempotencyKey(): string {
  const cryptoApi = globalThis.crypto;
  if (cryptoApi?.randomUUID) return cryptoApi.randomUUID();
  return `phase1e-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

function cursorQuery(value: Cursor | undefined): string | undefined {
  if (value === undefined) return undefined;
  return typeof value === 'bigint' ? value.toString() : String(value);
}

function pathPart(value: string, label: string): string {
  if (!value) throw new TypeError(`${label} must not be empty`);
  return encodeURIComponent(value);
}

export class Phase1EClient {
  readonly protocolVersion = PHASE1E_PROTOCOL_VERSION;
  readonly schemaDigest = PHASE1E_SCHEMA_DIGEST;
  private readonly baseUrl: string;
  private readonly transport: Phase1ETransport;
  private readonly clientVersion: string;
  private negotiated: ProtocolNegotiation | null = null;
  private responseMetadata: ResponseMetadata | null = null;

  constructor(
    baseUrl = 'http://127.0.0.1:8000',
    transport: Phase1ETransport = fetchPhase1ETransport,
    clientVersion = PHASE1E_PROTOCOL_VERSION,
  ) {
    this.baseUrl = baseUrl.replace(/\/+$/, '');
    this.transport = transport;
    this.clientVersion = clientVersion;
  }

  get lastResponse(): ResponseMetadata | null { return this.responseMetadata; }
  get negotiatedProtocol(): ProtocolNegotiation | null { return this.negotiated; }

  async negotiateProtocol(force = false): Promise<ProtocolNegotiation> {
    if (this.negotiated && !force) return this.negotiated;
    const response = await this.requestRaw({ method: 'GET', path: '/v1/protocol' }, true);
    const metadata = await readJson<ProtocolNegotiation>(response);
    if (
      metadata.protocol_version !== PHASE1E_PROTOCOL_VERSION ||
      metadata.min_client_version !== PHASE1E_PROTOCOL_VERSION
    ) {
      throw new ProtocolNegotiationError(
        `unsupported Core protocol: ${String(metadata.protocol_version)}`,
      );
    }
    if (metadata.schema_digest !== PHASE1E_SCHEMA_DIGEST) {
      throw new ProtocolNegotiationError(
        `Core Schema digest mismatch: expected ${PHASE1E_SCHEMA_DIGEST}, got ${metadata.schema_digest}`,
      );
    }
    if (!Array.isArray(metadata.capabilities)) {
      throw new ProtocolNegotiationError('Core protocol capabilities are invalid');
    }
    this.negotiated = metadata;
    return metadata;
  }

  private async ensureNegotiated(): Promise<void> { await this.negotiateProtocol(); }

  private async requestRaw(
    request: Omit<Phase1ERequest, 'url'> & { path: string; query?: Record<string, string | undefined>; },
    skipNegotiation = false,
  ): Promise<Phase1EResponse> {
    if (!skipNegotiation) await this.ensureNegotiated();
    const url = new URL(`${this.baseUrl}${request.path}`);
    for (const [key, value] of Object.entries(request.query ?? {})) {
      if (value !== undefined) url.searchParams.set(key, value);
    }
    let response: Phase1EResponse;
    try {
      response = await this.transport({
        ...request,
        url: url.toString(),
        headers: { 'X-Operant-Client-Version': this.clientVersion, ...(request.headers ?? {}) },
      });
    } catch (error: unknown) {
      if (error instanceof Phase1EError) throw error;
      throw new Phase1EError(
        'transport_unavailable',
        error instanceof Error ? error.message : 'transport request failed',
        true,
        'retry_later',
      );
    }
    const headers = responseHeaders(response.headers);
    this.responseMetadata = {
      status: response.status,
      idempotencyKey: headers['idempotency-key'],
      idempotencyReplayed: headers['idempotency-replayed']?.toLowerCase() === 'true',
    };
    if (response.status < 200 || response.status >= 300) throw await Phase1EError.fromResponse(response);
    return response;
  }

  async listProjects(options: ProjectListOptions = {}): Promise<ProjectProjection[]> {
    const response = await this.requestRaw({
      method: 'GET', path: '/v1/projects', headers: { Accept: 'application/json' },
      query: { after_cursor: cursorQuery(options.afterCursor), limit: options.limit === undefined ? undefined : String(options.limit) },
    });
    return readJson<ProjectProjection[]>(response);
  }

  async listWorkspaceFiles(workspaceId: string, options: WorkspaceFilesOptions = {}): Promise<WorkspaceFilesPage> {
    const response = await this.requestRaw({
      method: 'GET', path: `/v1/workspaces/${pathPart(workspaceId, 'workspaceId')}/files`,
      headers: { Accept: 'application/json' },
      query: {
        path: options.path,
        limit: options.limit === undefined ? undefined : String(options.limit),
        page_token: options.pageToken,
        snapshot: options.snapshot,
        after_name: options.afterName,
      },
    });
    return readJson<WorkspaceFilesPage>(response);
  }

  async listThreads(options: ThreadListOptions = {}): Promise<ThreadProjection[]> {
    const response = await this.requestRaw({
      method: 'GET', path: '/v1/threads', headers: { Accept: 'application/json' },
      query: {
        after_cursor: cursorQuery(options.afterCursor),
        limit: options.limit === undefined ? undefined : String(options.limit),
        parent_thread_id: options.parentThreadId,
        workspace_ref: options.workspaceRef,
        status: options.status,
      },
    });
    return readJson<ThreadProjection[]>(response);
  }

  async createSession(
    request: CreateSessionRequest,
    options: Phase1ERequestOptions = {},
  ): Promise<Session> {
    const response = await this.requestRaw({
      method: 'POST', path: '/v1/sessions',
      headers: {
        Accept: 'application/json', 'Content-Type': 'application/json',
        'Idempotency-Key': options.idempotencyKey ?? newIdempotencyKey(),
      },
      body: JSON.stringify(request),
    });
    return readJson<Session>(response);
  }

  async runSessionStream(
    sessionId: string,
    request: RunSessionRequest,
    options: RunSessionStreamOptions = {},
  ): Promise<RunSessionStream> {
    const response = await this.requestRaw({
      method: 'POST', path: `/v1/sessions/${pathPart(sessionId, 'sessionId')}/runs`,
      headers: {
        Accept: 'text/event-stream, application/json', 'Content-Type': 'application/json',
        'Idempotency-Key': options.idempotencyKey ?? newIdempotencyKey(),
        ...(options.lastEventId === undefined ? {} : { 'Last-Event-ID': String(options.lastEventId) }),
      },
      body: JSON.stringify(request),
    });
    const metadata = this.responseMetadata ?? { status: response.status, idempotencyReplayed: false };
    if (response.status === 202) {
      return { receipt: await readJson<CommandReceipt>(response), metadata, events: (async function*() {})() };
    }
    const source = response.body ?? await readText(response);
    return {
      receipt: null,
      metadata,
      events: (async function*() {
        for await (const frame of parseSse(source)) {
          const id = frame.id === undefined ? null : parseCursor(frame.id);
          yield {
            id,
            event: frame.event ?? 'message',
            data: frame.data,
            resource_scope: `session:${sessionId}`,
            stream_kind: 'session.run',
          };
        }
      })(),
    };
  }

  async listPendingApprovals(sessionId: string): Promise<ApprovalProjection[]> {
    const response = await this.requestRaw({
      method: 'GET', path: `/v1/sessions/${pathPart(sessionId, 'sessionId')}/approvals`,
      headers: { Accept: 'application/json' },
    });
    return readJson<ApprovalProjection[]>(response);
  }

  async submitApproval(
    sessionId: string,
    toolCallId: string,
    request: ApprovalDecisionRequest,
    options: Phase1ERequestOptions = {},
  ): Promise<ApprovalDecisionResult> {
    const response = await this.requestRaw({
      method: 'POST',
      path: `/v1/sessions/${pathPart(sessionId, 'sessionId')}/approvals/${pathPart(toolCallId, 'toolCallId')}`,
      headers: {
        Accept: 'application/json', 'Content-Type': 'application/json',
        'Idempotency-Key': options.idempotencyKey ?? newIdempotencyKey(),
      },
      body: JSON.stringify(request),
    });
    return readJson<ApprovalDecisionResult>(response);
  }
}

export { Phase1EError };
